### ISSUE TITLE
#764 #852

### ISSUE THREAD

**Issue by Blubagoo** [inspireui/support#1052]
Hey Guys, even after updating to the latest version of Beonews I am still unable to complete a build. We were successfully able to complete the IOS build and get it published but now its time for android and i desperately need the android version. I am unsure why this product is being sold if its unable to be built in android. That's false advertising and this needs to be fixed asap. 

Please let me know how you would like to proceed

**Comment by Blubagoo** [comment]
hi, could you provide and check the following info so that we could investigate your issues:

the screenshot issue
https://oneopinion.me/wp-content/uploads/2019/09/android-build-error.png

the detail log error when building the apk
```Error:Internal error: (java.lang.ClassNotFoundException) com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.util.indexing.counters.IndexCounters.<clinit>(IndexCounters.java:34)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:85)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex$CompilerMapReduceIndex.<init>(CompilerReferenceIndex.java:232)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex.<init>(CompilerReferenceIndex.java:79)
	at org.jetbrains.jps.backwardRefs.JavaCompilerBackwardReferenceIndex.<init>(JavaCompilerBackwardReferenceIndex.java:12)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexWriter.initialize(JavaBackwardReferenceIndexWriter.java:79)
	at org.jetbrains.jps.incremental.java.JavaBuilder.buildStarted(JavaBuilder.java:148)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:363)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:139)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:135)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:228)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

there are some known problem on android when changing the package name, please make sure you read this document - This has been done

**Comment by minhcasi** [comment]
@Blubagoo - could you compress the source and get back to support@inspireui.com so that we could check for this build issue - thanks

**Comment by Blubagoo** [comment]
I have started wetransfer with you guys so you should receive it soon.

**Comment by minhcasi** [comment]
Thank you, I got the package and forward to my team for checking, we will keep an update - very best!

**Comment by Blubagoo** [comment]
Ok thanks a bunch! I really need to get the android launched!

**Comment by concuacon** [comment]
Hello @Blubagoo I have checked your source, please check the your package name on the platform android, namely 3 files MainActivity.java, MainApplication.java and SplashActivity.java  have not been replaced by your package name, then you will be able to get the android launched.

**Comment by Blubagoo** [comment]
I was in the bin folder but not the src folder. That was my mistake but after changing the right set of files and file structure. I am still receiving the same build error

https://oneopinion.me/wp-content/uploads/2019/09/error.png

What environment are you using to build the apk? I am using android studio. Does the Keystore have to be built with shell? can I just use the android studio built-in Keystore creator?

**Comment by concuacon** [comment]
Hi @Blubagoo I use commandline to create keystore and build apk. 
Please check again to see if the files to change the package name have been changed? and try to follow these steps to make sure the project launch on Android: 
**cd android/ && ./gradlew clean && cd .../ && react-native run-android --variant=release**
If everything works well, then try to release again, or if the problem continues please attach the log file.

**Comment by Blubagoo** [comment]
Ok i will try tomorrow when i am back at work. Please do not close this case until i have told you it works or that i am unresponsive to a question.

**Comment by Blubagoo** [comment]
```Error:Internal error: (java.lang.ClassNotFoundException) com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.util.indexing.counters.IndexCounters.<clinit>(IndexCounters.java:34)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:85)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex$CompilerMapReduceIndex.<init>(CompilerReferenceIndex.java:232)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex.<init>(CompilerReferenceIndex.java:79)
	at org.jetbrains.jps.backwardRefs.JavaCompilerBackwardReferenceIndex.<init>(JavaCompilerBackwardReferenceIndex.java:12)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexWriter.initialize(JavaBackwardReferenceIndexWriter.java:79)
	at org.jetbrains.jps.incremental.java.JavaBuilder.buildStarted(JavaBuilder.java:148)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:363)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:139)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:135)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:228)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Blubagoo** [comment]
How much for you guys to take what i have and publish it?

**Comment by concuacon** [comment]
@Blubagoo you can see the price here: https://inspireui.com/services/

**Comment by tazar003** [comment]
Hi @minhcasi this case shouldn't have been closed. @concuacon requested we attach the log file if it didn't work and we did. We also asked for a price quote to get it published, that doesn't mean it was closed. Please reopen and @concuacon can you review the log file and help us determine what is happening?
