### ISSUE TITLE
[FluxStore - v 1.6.1 - WooCommerce] Blog not loading with exist errors.

### ISSUE THREAD

**Issue by interiorone** [inspireui/support#1755]
<img width="1440" alt="Screen Shot 2020-01-05 at 8 43 25 PM" src="https://user-images.githubusercontent.com/59524812/71777139-c6b36400-3000-11ea-821d-ee18134a2138.png">

![Screenshot_1578208571](https://user-images.githubusercontent.com/59524812/71777147-e2b70580-3000-11ea-86ce-c34db2aff7e6.png)

 Exception caught by widgets library 

The following NoSuchMethodError was thrown building BlogItemView(dirty, dependencies: [MediaQuery]):
The method '*' was called on null.
Receiver: null
Tried calling: *(1.2)

The relevant error-causing widget was: 
  BlogItemView file:///Users/dylan/Documents/Projects/Projects/InteriorOne_App/lib/widgets/home/horizontal/blog_list_items.dart:53:13
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Tools.image (package:fstore/common/tools.dart:83:62)
#2      BlogItemView.build (package:fstore/widgets/blog/blog_view.dart:70:34)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
...

Server Setting:

const serverConfig = {
  "type": "woo",
  "url": "https://interiorone.co.nz",
  "consumerKey": "ck_##hidden##",
  "consumerSecret": "cs_##hidden##",
  "blog": "https://interiorone.co.nz", //Your website woocommerce. You can remove this line if it same url
  "forgetPassword": "https://interiorone.co.nz/wp-login.php?action=lostpassword"
};

flutter doctor result below

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-NZ)
    • Flutter version 1.12.13+hotfix.5 at /Users/dylan/Documents/Projects/Tools/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dylan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by interiorone** [comment]
updated Proof of purchase

**Comment by interiorone** [comment]
Can you please help thank you.
