### ISSUE TITLE
[Fluxnews] Sign in with Apple 

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#2328]
Hello,
I would kindly request to test the "Sign in with Apple" on the Live production App.

https://itunes.apple.com/us/app/we-horse-racing/id1409165867 

Related to this https://github.com/inspireui/support/issues/2282

**Comment by minhcasi** [comment]
I've tested the previous version with Apple SignIn and it works fine, will also try the latest 2.4.1 and let you know - thank you!

**Comment by aldoyh** [comment]
Thank you so much for your time dear lovely team of @inspireui.
Now, this issue just came out of nowhere and I do not know what I have changed to get it!

![Simulator Screen Shot - iPhone 8 Plus - 2020-03-11 at 17 49 50](https://user-images.githubusercontent.com/5215449/76430805-cbf6ab80-63c1-11ea-969c-5cfe2306d144.png)

Here's the debug log:

```

2020-03-11 17:48:48.277559+0300 WeHorseRacing[96268:2328759] flutter: The following assertion was thrown building Builder:
2020-03-11 17:48:48.277713+0300 WeHorseRacing[96268:2328759] flutter: dependOnInheritedWidgetOfExactType<_LocalizationsScope>() or dependOnInheritedElement() was called
2020-03-11 17:48:48.277863+0300 WeHorseRacing[96268:2328759] flutter: before _OnBoardScreenState.initState() completed.
2020-03-11 17:48:48.277997+0300 WeHorseRacing[96268:2328759] flutter: When an inherited widget changes, for example if the value of Theme.of() changes, its dependent
2020-03-11 17:48:48.278114+0300 WeHorseRacing[96268:2328759] flutter: widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor
2020-03-11 17:48:48.278240+0300 WeHorseRacing[96268:2328759] flutter: or an initState() method, then the rebuilt dependent widget will not reflect the changes in the
2020-03-11 17:48:48.278350+0300 WeHorseRacing[96268:2328759] flutter: inherited widget.
2020-03-11 17:48:48.278480+0300 WeHorseRacing[96268:2328759] flutter: Typically references to inherited widgets should occur in widget build() methods. Alternatively,
2020-03-11 17:48:48.282191+0300 WeHorseRacing[96268:2328759] flutter: initialization based on inherited widgets can be placed in the didChangeDependencies method, which
2020-03-11 17:48:48.282336+0300 WeHorseRacing[96268:2328759] flutter: is called after initState and whenever the dependencies change thereafter.
2020-03-11 17:48:48.282487+0300 WeHorseRacing[96268:2328759] flutter:
2020-03-11 17:48:48.282633+0300 WeHorseRacing[96268:2328759] flutter: The relevant error-causing widget was:
2020-03-11 17:48:48.282787+0300 WeHorseRacing[96268:2328759] flutter:   MaterialApp file:///Users/aldoyh/Documents/apps/whr_app/lib/app.dart:167:20
2020-03-11 17:48:48.282926+0300 WeHorseRacing[96268:2328759] flutter:
2020-03-11 17:48:48.283040+0300 WeHorseRacing[96268:2328759] flutter: When the exception was thrown, this was the stack:
2020-03-11 17:48:48.283161+0300 WeHorseRacing[96268:2328759] flutter: #0      StatefulElement.dependOnInheritedElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:4467:9)
2020-03-11 17:48:48.283300+0300 WeHorseRacing[96268:2328759] flutter: #1      StatefulElement.dependOnInheritedElement (package:flutter/src/widgets/framework.dart:4510:6)
2020-03-11 17:48:48.283446+0300 WeHorseRacing[96268:2328759] flutter: #2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:3568:14)
2020-03-11 17:48:48.283611+0300 WeHorseRacing[96268:2328759] flutter: #3      Localizations.of (package:flutter/src/widgets/localizations.dart:448:47)
2020-03-11 17:48:48.283747+0300 WeHorseRacing[96268:2328759] flutter: #4      S.of (package:app/generated/l10n.dart:27:26)
2020-03-11 17:48:48.283866+0300 WeHorseRacing[96268:2328759] flutter: #5      _OnBoardScreenState.initState (package:app/screens/onboard_screen.dart:41:21)
2020-03-11 17:48:48.284003+0300 WeHorseRacing[96268:2328759] flutter: #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
2020-03-11 17:48:48.284138+0300 WeHorseRacing[96268:2328759] flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-03-11 17:48:48.284274+0300 WeHorseRacing[96268:2328759] flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-03-11 17:48:48.284403+0300 WeHorseRacing[96268:2328759] flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-03-11 17:48:48.284522+0300 WeHorseRacing[96268:2328759] flutter: #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-03-11 17:48:48.284641+0300 WeHorseRacing[96268:2328759] flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-03-11 17:48:48.284774+0300 WeHorseRacing[96268:2328759] flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-03-11 17:48:48.284895+0300 WeHorseRacing[96268:2328759] flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-03-11 17:48:48.285148+0300 WeHorseRacing[96268:2328759] flutter: #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-03-11 17:48:48.285507+0300 WeHorseRacing[96268:2328759] flutter: #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-03-11 17:48:48.286003+0300 WeHorseRacing[96268:2328759] flutter: #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-03-11 17:48:48.286392+0300 WeHorseRacing[96268:2328759] flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-03-11 17:48:48.286975+0300 WeHorseRacing[96268:2328759] flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-03-11 17:48:48.287185+0300 WeHorseRacing[96268:2328759] flutter: #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-03-11 17:48:48.287384+0300 WeHorseRacing[96268:2328759] flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-03-11 17:48:48.287669+0300 WeHorseRacing[96268:2328759] flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-03-11 17:48:48.287916+0300 WeHorseRacing[96268:2328759] flutter: #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-03-11 17:48:48.288195+0300 WeHorseRacing[96268:2328759] flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-03-11 17:48:48.288334+0300 WeHorseRacing[96268:2328759] flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-03-11 17:48:48.288522+0300 WeHorseRacing[96268:2328759] flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-03-11 17:48:48.288677+0300 WeHorseRacing[96268:2328759] flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-03-11 17:48:48.288812+0300 WeHorseRacing[96268:2328759] flutter: #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-03-11 17:48:48.288937+0300 WeHorseRacing[96268:2328759] flutter: #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
2020-03-11 17:48:48.289080+0300 WeHorseRacing[96268:2328759] flutter: #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-03-11 17:48:48.289235+0300 WeHorseRacing[96268:2328759] flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-03-11 17:48:48.289372+0300 WeHorseRacing[96268:2328759] flutter: #31     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
2020-03-11 17:48:48.289519+0300 WeHorseRacing[96268:2328759] flutter: #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-03-11 17:48:48.289668+0300 WeHorseRacing[96268:2328759] flutter: #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-03-11 17:48:48.289852+0300 WeHorseRacing[96268:2328759] flutter: #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-03-11 17:48:48.290032+0300 WeHorseRacing[96268:2328759] flutter: #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-03-11 17:48:48.290155+0300 WeHorseRacing[96268:2328759] flutter: #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-03-11 17:48:48.290284+0300 WeHorseRacing[96268:2328759] flutter: #37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
2020-03-11 17:48:48.290420+0300 WeHorseRacing[96268:2328759] flutter: #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-03-11 17:48:48.290551+0300 WeHorseRacing[96268:2328759] flutter: #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-03-11 17:48:48.290688+0300 WeHorseRacing[96268:2328759] flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-03-11 17:48:48.290821+0300 WeHorseRacing[96268:2328759] flutter: #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-03-11 17:48:48.290970+0300 WeHorseRacing[96268:2328759] flutter: #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-03-11 17:48:48.291148+0300 WeHorseRacing[96268:2328759] flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-03-11 17:48:48.291292+0300 WeHorseRacing[96268:2328759] flutter: #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
```


Here's **app.dart** which I compared with original copy looks the same!

```

import 'dart:async';
import 'dart:ui';

import 'package:after_layout/after_layout.dart';
import 'package:custom_splash/custom_splash.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_analytics/observer.dart';
import 'package:flare_splash_screen/flare_splash_screen.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'common/config.dart';
import 'common/constants.dart';
import 'common/styles.dart';
import 'common/tools.dart';
import 'models/app.dart';
import 'models/blog_news.dart';
import 'models/category.dart';
import 'models/product.dart';
import 'models/recent_product.dart';
import 'models/search.dart';
import 'models/user.dart';
import 'models/wishlist.dart';
import 'screens/blogs.dart';
import 'screens/login.dart';
import 'screens/notification.dart';
import 'screens/onboard_screen.dart';
import 'screens/registration.dart';
import 'screens/wishlist.dart';
import 'services/wordpress.dart';
import 'tabbar.dart';

import 'generated/l10n.dart';

FirebaseAnalytics analytics = FirebaseAnalytics();

class App extends StatefulWidget {
  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle.dark
          .copyWith(statusBarColor: Theme.of(context).accentColor),
    );
    // to hide only status bar:
    SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);

    /// For Flare Image
    if (kSplashScreen.lastIndexOf('flr') > 0) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: SplashScreen.navigate(
          name: kSplashScreen,
          // TODO: Splashscreen animation start command
          startAnimation: 'Aura2',
          backgroundColor: Colors.white,
          next: (object) => MyApp(),
          until: () => Future.delayed(Duration(seconds: 3)),
        ),
      );
    }

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: CustomSplash(
        imagePath: kLogoImage,
        backGroundColor: Colors.white,
        animationEffect: 'fade-in',
        logoSize: 80,
        home: MyApp(),
        duration: 3500,
      ),
    );
  }
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return AppState();
  }
}

class AppState extends State<MyApp> with AfterLayoutMixin {
  final _app = AppModel();
  final _product = ProductModel();
  final _wishlist = WishListModel();
  final _search = SearchModel();
  final _recent = RecentModel();
  final _blog = BlogNewsModel();
  bool isFirstSeen = false;
  bool isChecking = true;
  bool isLoggedIn = false;

  @override
  void afterFirstLayout(BuildContext context) async {
    WordPress().setAppConfig(serverConfig);
    _app.loadAppConfig();
    isFirstSeen = await checkFirstSeen();
    isLoggedIn = await checkLogin();
    setState(() {
      isChecking = false;
    });
  }

  Future checkFirstSeen() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    bool _seen = (prefs.getBool('seen') ?? false);

    if (_seen)
      return false;
    else {
      prefs.setBool('seen', true);
      return true;
    }
  }

  Future checkLogin() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    return prefs.getBool('loggedIn') ?? false;
  }

  Widget renderFirstScreen() {
    if (isFirstSeen) return OnBoardScreen();
    if (kAdvanceConfig['IsRequiredLogin'] && !isLoggedIn) return LoginScreen();
    return MainTabs();
  }

  @override
  Widget build(BuildContext context) {
    if (isChecking) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          body: Container(),
        ),
      );
    }

    return ChangeNotifierProvider<AppModel>.value(
      value: _app,
      child: Consumer<AppModel>(
        builder: (context, value, child) {
          if (value.isLoading) {
            return Container(
              color: Colors.white,
            );
          }
          return MultiProvider(
            providers: [
              Provider<ProductModel>.value(value: _product),
              Provider<BlogNewsModel>.value(value: _blog),
              Provider<WishListModel>.value(value: _wishlist),
              Provider<SearchModel>.value(value: _search),
              Provider<RecentModel>.value(value: _recent),
              ChangeNotifierProvider(create: (_) => UserModel()),
              ChangeNotifierProvider(create: (_) => CategoryModel()),
              ChangeNotifierProvider(create: (_) => _blog)
            ],
            child: MaterialApp(
              debugShowCheckedModeBanner: false,
              locale: Locale(
                  Provider.of<AppModel>(context, listen: false).locale, ""),
              navigatorObservers: [
                FirebaseAnalyticsObserver(analytics: analytics),
              ],
              localizationsDelegates: [
                S.delegate,
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
              ],
              supportedLocales: S.delegate.supportedLocales,
              home: renderFirstScreen(),
              routes: <String, WidgetBuilder>{
                "/home": (context) => MainTabs(),
                "/login": (context) => LoginScreen(),
                "/register": (context) => RegistrationScreen(),
                '/wishlist': (context) => WishList(),
                '/blogs': (context) => BlogScreen(),
                '/notify': (context) => Notifications()
              },
              theme: Provider.of<AppModel>(context).darkTheme
                  ? buildDarkTheme().copyWith(
                      primaryColor:
                          HexColor(_app.appConfig["Setting"]["MainColor"]))
                  : buildLightTheme().copyWith(
                      primaryColor:
                          HexColor(_app.appConfig["Setting"]["MainColor"])),
            ),
          );
        },
      ),
    );
  }
}

```

**Comment by aldoyh** [comment]
I've changed the flutter channel to beta then master and still the same. Please any help would be greatly appreciated. Thanks.

**Comment by minhcasi** [comment]
@dttrung26 - please help for investigating

**Comment by aldoyh** [comment]
Thanks in advance Mr. @dttrung26 ,
Now, this is showing on Android version, I have no idea what I'm doing wrong?
I think it could be the localization problem, please help.

The Error:
```

I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
    The following NoSuchMethodError was thrown building Consumer<AppModel>(dirty, dependencies:
    [InheritedProvider<AppModel>]):
    The method '[]' was called on null.
    Receiver: null
    Tried calling: []("Setting")
    The relevant error-causing widget was:
      Consumer<AppModel> file:///Users/aldoyh/Documents/apps/whr_app/lib/app.dart:149:14
    When the exception was thrown, this was the stack:
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      AppState.build.<anonymous closure> (package:app/app.dart:195:50)
I/flutter: #2      Consumer.build (package:provider/src/consumer.dart:180:12)
    #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
    #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
    #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
    #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
    #7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
    #8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
    #9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
    #10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
    #11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
    #15     _invoke (dart:ui/hooks.dart:259:10)
    #16     _drawFrame (dart:ui/hooks.dart:217:3)
    (elided 3 frames from package dart:async)
    ════════════════════════════════════════════════════════════════════════════════════════════════════

```

![Screenshot_1584095351](https://user-images.githubusercontent.com/5215449/76613174-ae932000-652e-11ea-82dd-012a5397030b.png)

**Comment by dttrung26** [comment]
Hi @aldoyh ,

would you please kindly leave your common folder here as well as skype in case Teamview needed. 

Have a nice weekend,
Trung.

**Comment by aldoyh** [comment]
Hello,

Here you go:
[common.zip](https://github.com/inspireui/support/files/4340691/common.zip)

My skype is @bukowari 

Your help is very much appreciated.

**Comment by dttrung26** [comment]
Support via skype.
