### ISSUE TITLE
Fluxstore listing failed to build ios

### ISSUE THREAD

**Issue by youngtet** [inspireui/support#2464]
fail to build iOS, it crashes

here is the log

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build ios --debug

## exception

ProcessException: ProcessException: Process timed out:

  Command: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet DEVELOPMENT_TEAM=V448PRHVN3 -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/tetley/Downloads/FluxStore-listing 1.3.0/source/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/23/x2cb1dn955qcrgp9p1sthzhr0000gn/T/flutter_build_log_pipe.xfvMpN/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:346:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:503:66)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#21     _rootRunUnary (dart:async/zone.dart:1134:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#28     _rootRun (dart:async/zone.dart:1126:13)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15 19A471t, locale en-TZ)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at /Users/tetley/Developer/flutter
    [32m•[39m Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that
      location.
      You may also want to add it to your PATH environment variable.


[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.0, Build version 11A420a
    [32m•[39m CocoaPods version 1.9.1

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.43.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.8.1

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 3 categories.
```

**Comment by youngtet** [comment]
![Van](https://user-images.githubusercontent.com/60430933/77707411-5f021a80-6f58-11ea-867e-6c98372853e7.jpg)

proof of purchase

**Comment by minhcasi** [comment]
@youngtet - could you help to clean cache issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by youngtet** [comment]
![image](https://user-images.githubusercontent.com/60430933/77785751-ab8b4a00-706d-11ea-94c9-2dc4808ebcdb.jpg)

**Comment by youngtet** [comment]
![image](https://user-images.githubusercontent.com/60430933/77785941-fe650180-706d-11ea-9ed7-70f2cd3756d7.jpg)

**Comment by youngtet** [comment]
when i pod install

**Comment by minhcasi** [comment]
@youngtet - could you try this solution 

Go to ios folder: remove Pods folder, Podfile and fodfile.lock
Open XCode, File > Workspace Settings > Select 'New Build System' - https://tppr.me/CRHLC
Open terminal (at ios folder) and run:
```
pod repo update
pod install
```

**Comment by youngtet** [comment]
during the pod install it says "No 'Podfile' found in the project directory

**Comment by minhcasi** [comment]
@youngtet - try to go ios folder pls

**Comment by youngtet** [comment]
i have, but the issue is still there when i checked the notification_permission file i saw the LICENSE file saved as LICENSE.md so it can't find it... do i rename the file or update the path on the notification_permissions.podspec?

**Comment by minhcasi** [comment]
@youngtet - please check this XCode migration you are using latest XCode 11.4  - https://flutter.dev/docs/development/ios-project-migration

**Comment by youngtet** [comment]
I'm using X-code 11

**Comment by youngtet** [comment]
![image](https://user-images.githubusercontent.com/60430933/77985663-c08e0480-731d-11ea-879f-d1a5d8f0b073.jpg)

i'm getting this error while Archiving on xcode

**Comment by minhcasi** [comment]
@youngtet - let try with some solution to clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Please make sure you run the app from the Android Studio, instead of running from XCode

We also upload new release for Fluxlisting on tomorrow - thank you!

**Comment by minhcasi** [comment]
@youngtet - please update the latest Fluxstore Listing version to fix the issue
