### ISSUE TITLE
[FluxStore Pro] - Stripe Error

### ISSUE THREAD

**Issue by xLidoni** [inspireui/support#2722]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Hello!

I've enabled Stripe Gateway, but i have similar problem : https://github.com/inspireui/support/issues/2677

Any solution?

Thanks!!

2. Screenshots issues (required):

![Screenshot (138)](https://user-images.githubusercontent.com/11965301/79279903-5cd41180-7eaf-11ea-917c-3c520340c458.png)

I have tried several versions of Stripe Plugins, but the result doesn't change.

3. Proof of my purchased (required):

![image](https://user-images.githubusercontent.com/11965301/79279884-4e85f580-7eaf-11ea-9a96-e4f54670ce39.png)

3. Config files (required)

**Comment by minhtruong315** [comment]
@xLidoni you can try to use one page checkout
https://tppr.me/F0rnZ

**Comment by xLidoni** [comment]
Thanks for your reply!

https://tppr.me/F0rnZ the link doesn't work!

**Comment by xLidoni** [comment]
Where i have to enable one pg checkout?

**Comment by minhtruong315** [comment]
<img width="1139" alt="Screen Shot 2020-04-16 at 7 01 06 AM" src="https://user-images.githubusercontent.com/10402500/79400321-1c0ff180-7fb0-11ea-9d3f-58f187cba6bb.png">

**Comment by minhcasi** [comment]
Please move your all conversation to the same #2722 - thank you!

**Comment by xLidoni** [comment]
Hello!

For the image problems, **i've fixed**!

It caused by .png extension on wordpress.
I've created image with .jpg extension.
Works Fine!

**Comment by xLidoni** [comment]
@minhcasi If i enable  one step checkout , will open webview mhh..

**Comment by xLidoni** [comment]
@minhcasi If i enable one step checkout , will open webview mhh..


![image](https://user-images.githubusercontent.com/11965301/79442976-85582a80-7fd9-11ea-94b5-7a81fc78e2e4.png)





I've second issue.

When i try to use paypal and i **select** "Type Card" , app crash!

Please, watch this video : 

https://youtu.be/0CEnyyE3r6c



```
I/chatty  (15902): uid=10133(com.inspireui.fluxstore) Chrome_InProcGp identical 2 lines
E/eglCodecCommon(15902): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon(15902): glUtilsParamSize: unknow param 0x000088ef
I/chatty  (15902): uid=10133(com.inspireui.fluxstore) Chrome_InProcGp identical 2 lines
E/eglCodecCommon(15902): glUtilsParamSize: unknow param 0x000088ef
I/chromium(15902): [INFO:CONSOLE(0)] "Refused to load the image 'https://www.google-analytics.com/r/collect?v=1&_v=j79&aip=1&a=14378968&t=pageview&_s=1&dl=https%3A%2F%2Fwww.sandbox.paypal.com%2Fcgi-bin%2Fwebscr%3Fcmd%3D_express-checkout%26token%3DEC-4CG18760054538221&ul=en-us&de=UTF-8&dt=Accedi%20al%20tuo%20conto%20PayPal&sd=24-bit&sr=412x604&vp=412x604&je=0&_u=ACCACUABB~&jid=721419914&gjid=1544362732&cid=325345282.1586959603&tid=UA-53389718-12&_gid=1755713596.1586959603&_r=1&cd1=325345282.1586959603&cd2=&cd3=0&cd4=https%3A%2F%2Fwww.sandbox.paypal.com%2Fcgi-bin%2Fwebscr&cd5=it&cd6=&cd7=&cd8=&cd9=&cd10=unifiedloginnodeweb&cd19=&cd20=&cd22=main%3Aunifiedlogin%3Asplitlogin%3A%3Aemail&cd25=7e29c30f171ac120001822c9ffff947f&cd26=0&gtm=2oi3b2&z=1319930692' because it violates the following Content Security Policy directive: "img-src 'self' https://*.googleusercontent.com/ https://*.paypalobjects.com https://ak1s.abmr.net https://ak1s.mathtag.com https://akamai.mathtag.com https://ak1.abmr.net https://*.paypal.com".
I/chromium(15902): ", source: https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-4CG18760054538221 (0)
D/EGL_emulation(15902): eglMakeCurrent: 0xe3a39080: ver 3 1 (tinfo 0xeed89560)
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,2112}
D/EGL_emulation(15902): eglMakeCurrent: 0xe3a39080: ver 3 1 (tinfo 0xeed89560)
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,2112}
I/chromium(15902): [INFO:CONSOLE(430)] "Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-ughP/xSOtwg/DVOT+TTKxJxUCxueRoCd1YuKhSsrGGs1Ddpk' 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline' 'unsafe-eval'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
I/chromium(15902): ", source: https://www.sandbox.paypal.com/webapps/xoonboarding?token=EC-4CG18760054538221&country.x=IT&locale.x=it_IT&locale.x=it_IT&country.x=IT (430)
I/chromium(15902): [INFO:CONSOLE(491)] "Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-ughP/xSOtwg/DVOT+TTKxJxUCxueRoCd1YuKhSsrGGs1Ddpk' 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline' 'unsafe-eval'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
I/chromium(15902): ", source: https://www.sandbox.paypal.com/webapps/xoonboarding?token=EC-4CG18760054538221&country.x=IT&locale.x=it_IT&locale.x=it_IT&country.x=IT (491)
I/chromium(15902): [INFO:CONSOLE(492)] "Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-ughP/xSOtwg/DVOT+TTKxJxUCxueRoCd1YuKhSsrGGs1Ddpk' 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline' 'unsafe-eval'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
I/chromium(15902): ", source: https://www.sandbox.paypal.com/webapps/xoonboarding?token=EC-4CG18760054538221&country.x=IT&locale.x=it_IT&locale.x=it_IT&country.x=IT (492)
I/chromium(15902): [INFO:CONSOLE(551)] "Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-ughP/xSOtwg/DVOT+TTKxJxUCxueRoCd1YuKhSsrGGs1Ddpk' 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline' 'unsafe-eval'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
I/chromium(15902): ", source: https://www.sandbox.paypal.com/webapps/xoonboarding?token=EC-4CG18760054538221&country.x=IT&locale.x=it_IT&locale.x=it_IT&country.x=IT (551)
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,2112}
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,2112}
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,2112}
I/chatty  (15902): uid=10133(com.inspireui.fluxstore) identical 1 line
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,2112}
W/cr_AwAutofillManager(15902): WebView autofill is disabled because WebView isn't created with activity context.
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,2112}
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,2112}
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,2112}
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,2112}
I/flutter (15902): [Fluxstore][AppState] build
I/flutter (15902): [Fluxstore][Tabbar] build
I/flutter (15902): https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-4CG18760054538221
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. ......ID 0,0-1440,2112}
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. ......ID 0,0-1440,2112}
D/EGL_emulation(15902): eglMakeCurrent: 0xe3a39080: ver 3 1 (tinfo 0xeed89560)
E/eglCodecCommon(15902): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon(15902): glUtilsParamSize: unknow param 0x000088ef
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=14 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. .F...... 0,0-1440,1125}
W/IInputConnectionWrapper(15902): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15902): getTextAfterCursor on inactive InputConnection
I/flutter (15902): [Fluxstore][AppState] build
I/flutter (15902): [Fluxstore][Tabbar] build
I/flutter (15902): https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-4CG18760054538221
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=14 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. ......ID 0,0-1440,1125}
E/InputMethodManager(15902): b/117267690: Failed to get fallback IMM with expected displayId=14 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7d5e9d4 VFEDHVC.. ......ID 0,0-1440,1125}
D/EGL_emulation(15902): eglMakeCurrent: 0xe3a39080: ver 3 1 (tinfo 0xeed89560)
E/eglCodecCommon(15902): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon(15902): glUtilsParamSize: unknow param 0x000088ef
W/System.err(15902): java.lang.ClassCastException: $Proxy0 cannot be cast to android.view.WindowManagerImpl
W/System.err(15902): 	at android.view.Window.setWindowManager(Window.java:778)
W/System.err(15902): 	at android.view.Window.setWindowManager(Window.java:760)
W/System.err(15902): 	at android.app.Dialog.<init>(Dialog.java:207)
W/System.err(15902): 	at android.app.AlertDialog.<init>(AlertDialog.java:204)
W/System.err(15902): 	at android.app.AlertDialog$Builder.create(AlertDialog.java:1105)
W/System.err(15902): 	at JB.<init>(PG:6)
W/System.err(15902): 	at org.chromium.content.browser.input.SelectPopup.show(PG:41)
W/System.err(15902): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(15902): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err(15902): 	at android.os.Looper.loop(Looper.java:174)
W/System.err(15902): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(15902): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15902): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(15902): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
F/chromium(15902): [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
F/libc    (15902): Fatal signal 5 (SIGTRAP), code 128 (SI_KERNEL), fault addr 0x0 in tid 15902 (ireui.fluxstore), pid 15902 (ireui.fluxstore)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.191030.002/5978551:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-04-16 10:33:34+0000
pid: 15902, tid: 15902, name: ireui.fluxstore  >>> com.inspireui.fluxstore <<<
uid: 10133
signal 5 (SIGTRAP), code 128 (SI_KERNEL), fault addr 0x0
Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
'
    eax 00000000  ebx cfd78864  ecx bc53a1c0  edx 00000400
    edi ed3a5980  esi ffdcf0e0
    ebp bc53a1c0  esp ffdcec70  eip cd35fc30
backtrace:
      #00 pc 01cfdc30  /system/product/app/TrichromeLibrary/TrichromeLibrary.apk!libmonochrome.so (offset 0x66c000) (BuildId: ffe50d4377c82928759c1f40f1b35ba9f411454a)

```

**Comment by minhtruong315** [comment]
@xLidoni can u send me config files via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2722

**Comment by minhtruong315** [comment]
@xLidoni I checked your source code, OnePageCheckout is working well. 
<img width="1104" alt="Screen Shot 2020-04-22 at 8 31 12 AM" src="https://user-images.githubusercontent.com/10402500/79930829-b28e5800-8473-11ea-874b-5661b0883cae.png">
https://www.dropbox.com/s/hgl2myx4cxesp0e/payment.mov?dl=0

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by xLidoni** [comment]
Hi, yes the one step checkout works, but it doesn't work without, can you check?

With paypal it doesn't work, when I click on select the card the app closes. Check the video gently.
