### ISSUE TITLE
Expo Error

### ISSUE THREAD

**Issue by mryous** [inspireui/support#2909]
![image](https://user-images.githubusercontent.com/28628432/80462518-6b1f3480-8969-11ea-8ddf-0520153c1441.png)

Your project is in SDK version >= 33.0.0, but the expo package version seems to be older.
Error: node_modules directory is missing. Please run `npm install` in your project directory.
Couldn't start project. Please fix the errors and restart the project.

in Browser :
Expo Developer Tools is disconnected from Expo CLI. Use the expo start command to start the CLI again.

**Comment by luyx2412** [comment]
Hi @mryous Please run `npm install` or `yarn install` before start project.

Thanks

**Comment by mryous** [comment]
![image](https://user-images.githubusercontent.com/28628432/80497824-8c017d00-899d-11ea-9339-5200984e9d04.png)

I got that before start the project

**Comment by mryous** [comment]
```
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning babel-preset-env > babel-plugin-check-es2015-constants > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > fbjs-scripts > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > metro-babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
This happen when i start the project through Ce Builder

and when I start Expo

```
Starting project at D:\AndroidStudio\mstore-multi-vendor-v1.3.3\mstore-mv-expo
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Your project is in SDK version >= 33.0.0, but the expo package version seems to be older.
Error: node_modules directory is missing. Please run `npm install` in your project directory.
Couldn't start project. Please fix the errors and restart the project.
Error: Couldn't start project. Please fix the errors and restart the project.
    at startExpoServerAsync (C:\@expo\xdl@57.8.32\src\Project.ts:1948:11)
    at Object.startAsync (C:\@expo\xdl@57.8.32\src\Project.ts:2350:5)
    at action (C:\Users\****\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:163:3)
    at C:\Users\****\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:334:16
    at Command.<anonymous> (C:\Users\mryou\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:84:7)
```
plz help me sir

**Comment by mryous** [comment]
*note : I move the project to other directory, I'm afraid my '-work-' directory might use a forbidden character (-)

**Comment by mryous** [comment]
hallo siiirr @luyx2412 @minhcasi plzz helo mee

**Comment by minhcasi** [comment]
@mryous - pls try to install this lib to fix the git issue - https://git-scm.com/download/win

**Comment by mryous** [comment]
thank you sir.., wil try it

**Comment by mryous** [comment]
and... yes.. its still wont work for me... 
what is your suggestion for me now? thnks

**Comment by luyx2412** [comment]
Hi @mryous The first please update your expo to latest version. And please try install again.
![image](https://user-images.githubusercontent.com/8909619/80680049-49988700-8ae8-11ea-8405-3fda03b3727f.png)

Thanks
