### ISSUE TITLE
Payment Issue [Woo-Fluxstore 1.7.1]

### ISSUE THREAD

**Issue by iamar1k92** [inspireui/support#2995]
Step 1 (require): detail issues and screenshots

PROBLEM 1: We are facing payment method issue. Only Cash on delivery, Paypal in app are working in our mobile app. There is another payment method redsys which is integrated on woo-commerce plugin. & This payment method is working ok on website. But in app, it causes problems. I tried to use both native/enable one page checkout but none of them work for us. It always gives the following error. I repeat i have used the enable one page option as well. It has same result.
https://imgur.com/a/8wPXXaK

PROBLEM 2: Why we cannot change the profile details dynamically. When we change the profile details, those are store on the particular session of the local device. When the app get closed, the profile data return back to it initial value, anyhow, there is no use of changing the name etc as it is not having backend.

PROBLEM 3: Please add backend support to save user phone number either on wordpress database or it stores on user's device at least temporary as it doesn't get lost as user quits the app.

COMMON PROBLEMS: 1- Please fix the cart pricing, as it shows the original price of the app instead of discounted one asap.
2- Please fix: It cannot show all products of particular category in horizontal scroll view on home screen using config. It should at-least show all of them. 
3- Same issue with see all, it also didn't show all products.

Step 2 (require): SENT!!!

**Comment by iamar1k92** [comment]
Another issue: https://imgur.com/a/60rtOGK
It doesn't load splash screen app crashes with this error.

**Comment by iamar1k92** [comment]
Please provide the solution, we don't have much time for this.
PROBLEM 1: We are facing payment method issue. Only Cash on delivery, Paypal in app are working in our mobile app. There is another payment method redsys which is integrated on woo-commerce plugin. & This payment method is working ok on website. But in app, it causes problems. I tried to use both native/enable one page checkout but none of them work for us. It always gives the following error. I repeat i have used the enable one page option as well. It has same result.
https://imgur.com/a/8wPXXaK

PROBLEM 2: Why we cannot change the profile details dynamically. When we change the profile details, those are store on the particular session of the local device. When the app get closed, the profile data return back to it initial value, anyhow, there is no use of changing the name etc as it is not having backend.

PROBLEM 3: Please add backend support to save user phone number either on wordpress database or it stores on user's device at least temporary as it doesn't get lost as user quits the app.

**Comment by minhtruong315** [comment]
@iamar1k92 can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2995
Thanks

**Comment by iamar1k92** [comment]
sent.

**Comment by minhtruong315** [comment]
can u  change English language on your admin site?

**Comment by iamar1k92** [comment]
well ok, i will do it.

**Comment by iamar1k92** [comment]
@minhtruong315 it's changed to English.

**Comment by iamar1k92** [comment]
Please check...

**Comment by minhtruong315** [comment]
@iamar1k92 your website is showing error when checkout
You can check this url: https://lemarchexpress.com/checkout?code=b61fbefd1a422b37b31b711ebea70e89&mobile=true
Can u send me ftp info via my email? I will enable debug mode to check log

**Comment by iamar1k92** [comment]
ftp info sent!

**Comment by minhtruong315** [comment]
@iamar1k92 pls relay on the email.

**Comment by iamar1k92** [comment]
i have replied, please move ahead. We don't have much time already.

**Comment by minhtruong315** [comment]
<img width="543" alt="Screen Shot 2020-05-11 at 9 21 02 AM" src="https://user-images.githubusercontent.com/10402500/81518602-c3423780-9368-11ea-9d8f-be8c65f93b2f.png">
I can't access to your host via ftp.  Can u help me enable debug mode for your website?

**Comment by minhcasi** [comment]
@iamar1k92 - could you hep to update on the ticket?

**Comment by iamar1k92** [comment]
i have enabled the debug mode, and replied via email already.

**Comment by minhtruong315** [comment]
@iamar1k92 Can u help me check this link? 
https://lemarchexpress.com/checkout?code=b61fbefd1a422b37b31b711ebea70e89&mobile=true
it doesn't show error log

**Comment by iamar1k92** [comment]
[wp-config.txt](https://github.com/inspireui/support/files/4620740/wp-config.txt)
this is the wp-config.php file after enable the debug mode.

**Comment by iamar1k92** [comment]
<?php
/**
 * The base configuration for WordPress
 *
 * The wp-config.php creation script uses this file during the
 * installation. You don't have to use the web site, you can
 * copy this file to "wp-config.php" and fill in the values.
 *
 * This file contains the following configurations:
 *
 * * MySQL settings
 * * Secret keys
 * * Database table prefix
 * * ABSPATH
 *
 * @link https://codex.wordpress.org/Editing_wp-config.php
 *
 * @package WordPress
 */

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define( 'DB_NAME', 'dbbc23pdvp2qpw' );

/** MySQL database username */
define( 'DB_USER', 'u4pmcgrb6gphm' );

/** MySQL database password */
define( 'DB_PASSWORD', 'emvbxpz3bc23' );

/** MySQL hostname */
define( 'DB_HOST', '127.0.0.1' );

/** Database Charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8' );

/** The Database Collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );

/**
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
define( 'AUTH_KEY',          'r9@=l8<{&`+qUgO#7_C7_=!SA+@^GK<aY9W/HV_hmQ6kMWTdT>2)y<{/P[IpRS{j' );
define( 'SECURE_AUTH_KEY',   'JFabTCDN~VU0:=/(@eRz.m-5ZG/XjxJ>olT+Fx5`or-~gzH]>ZAS}8IT*h;#A+hb' );
define( 'LOGGED_IN_KEY',     'fYlS*VLs;wfbT;v2jh*2%$xV~_DP-5+.3%!t,_,IM?(L%S3+<@=%(U{k|u}Iaz*.' );
define( 'NONCE_KEY',         '<_:2OzehEmA $(WiNSBCL#vmpTC8t(QE9I0QbNR!_E775dY@hnl?.Ya56pS/Qro&' );
define( 'AUTH_SALT',         'fmlG&yo-Bl(X?!g/&g[#CgM1|0|&g*nvN E,xbL/xctjch/FDT2NXfGaFy-nra+z' );
define( 'SECURE_AUTH_SALT',  '/+tV|R4or)0cM,;`,)M5TpdBQ*YpPi2yc2z]-Vw3rW@![R{${`>Tg?9W;2V9sbX^' );
define( 'LOGGED_IN_SALT',    'ZF7&*]v%iuH_}}A*r6{mW42h>ZHSF&2lGUx.oT^xE]v5$a$H%KMNaX>/gk_EKuUC' );
define( 'NONCE_SALT',        'cD!m#uBDHe:!OSq1,ry#acsc}Q9eRsypuzvp#(f(Wj]@UC>ed<wNj1tX}h^q2-mh' );
define( 'WP_CACHE_KEY_SALT', '(LG7O=b$GkXTTT 09rGE IU+` @^4/i2ait>mX->=WAm#Ut$sH(u>$76`IFDG!a(' );

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
$table_prefix = 'lqk_';
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);

define('WP_MEMORY_LIMIT', '256M');

/* That's all, stop editing! Happy publishing. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', dirname( __FILE__ ) . '/' );
}


/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
@include_once('/var/lib/sec/wp-settings.php'); // Added by SiteGround WordPress management system

**Comment by iamar1k92** [comment]
[11-May-2020 21:13:34 UTC] Error Deadlock found when trying to get lock; try restarting transaction de la base de datos de WordPress para la consulta DELETE FROM `lqk_options` WHERE `option_name` = '_transient_timeout_jetpack_idc_allowed' realizada por require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\Jetpack\Config->on_plugins_loaded, Automattic\Jetpack\Config->ensure_feature, Automattic\Jetpack\Config->enable_sync, Automattic\Jetpack\Sync\Main::configure, Automattic\Jetpack\Sync\Actions::sync_allowed, Automattic\Jetpack\Status->is_staging_site, Jetpack::validate_sync_error_idc_option, get_transient, delete_option
[11-May-2020 21:13:34 UTC] Error Deadlock found when trying to get lock; try restarting transaction de la base de datos de WordPress para la consulta DELETE FROM `lqk_options` WHERE `option_name` = '_transient_timeout_jetpack_idc_allowed' realizada por require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\Jetpack\Config->on_plugins_loaded, Automattic\Jetpack\Config->ensure_feature, Automattic\Jetpack\Config->enable_sync, Automattic\Jetpack\Sync\Main::configure, Automattic\Jetpack\Sync\Actions::sync_allowed, Automattic\Jetpack\Status->is_staging_site, Jetpack::validate_sync_error_idc_option, get_transient, delete_option
[11-May-2020 21:13:34 UTC] Error Deadlock found when trying to get lock; try restarting transaction de la base de datos de WordPress para la consulta DELETE FROM `lqk_options` WHERE `option_name` = '_transient_timeout_jetpack_idc_allowed' realizada por require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\Jetpack\Config->on_plugins_loaded, Automattic\Jetpack\Config->ensure_feature, Automattic\Jetpack\Config->enable_sync, Automattic\Jetpack\Sync\Main::configure, Automattic\Jetpack\Sync\Actions::sync_allowed, Automattic\Jetpack\Status->is_staging_site, Jetpack::validate_sync_error_idc_option, get_transient, delete_option
[11-May-2020 21:13:34 UTC] Error Deadlock found when trying to get lock; try restarting transaction de la base de datos de WordPress para la consulta DELETE FROM `lqk_options` WHERE `option_name` = '_transient_timeout_jetpack_idc_allowed' realizada por require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\Jetpack\Config->on_plugins_loaded, Automattic\Jetpack\Config->ensure_feature, Automattic\Jetpack\Config->enable_sync, Automattic\Jetpack\Sync\Main::configure, Automattic\Jetpack\Sync\Actions::sync_allowed, Automattic\Jetpack\Status->is_staging_site, Jetpack::validate_sync_error_idc_option, get_transient, delete_option
[11-May-2020 21:13:39 UTC] WordPress database error Deadlock found when trying to get lock; try restarting transaction for query DELETE FROM `lqk_options` WHERE `option_name` = '_transient_timeout_jetpack_sync_constants_await' made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\Jetpack\Sync\Sender->do_sync, Automattic\Jetpack\Sync\Sender->do_sync_and_set_delays, Automattic\Jetpack\Sync\Sender->do_sync_for_queue, do_action('jetpack_sync_before_send_queue_sync'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\Jetpack\Sync\Modules\Constants->maybe_sync_constants, get_transient, delete_option
[11-May-2020 21:14:38 UTC] id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WC_REST_CRUD_Controller->update_item, WC_REST_Orders_V2_Controller->save_object, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, wc_order_fully_refunded, wc_create_refund, do_action('woocommerce_order_fully_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_fully_refunded_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Refunded_Order->trigger_full, WC_Email_Customer_Refunded_Order->trigger, WC_Email->get_content, WC_Email_Customer_Refunded_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-refunded-order.php'), do_action('woocommerce_email_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails->order_details, wc_get_template, include('/plugins/woocommerce/templates/emails/email-order-details.php'), do_action('woocommerce_email_after_order_table'), WP_Hook->do_action, WP_Hook->apply_filters, byconsolewooodt_woocommerce_email_after_order_table, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.
[11-May-2020 21:14:38 UTC] id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WC_REST_CRUD_Controller->update_item, WC_REST_Orders_V2_Controller->save_object, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, wc_order_fully_refunded, wc_create_refund, do_action('woocommerce_order_fully_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_fully_refunded_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Refunded_Order->trigger_full, WC_Email_Customer_Refunded_Order->trigger, WC_Email->get_content, WC_Email_Customer_Refunded_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-refunded-order.php'), do_action('woocommerce_email_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails->order_details, wc_get_template, include('/plugins/woocommerce/templates/emails/email-order-details.php'), do_action('woocommerce_email_after_order_table'), WP_Hook->do_action, WP_Hook->apply_filters, byconsolewooodt_woocommerce_email_after_order_table, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.
[11-May-2020 21:14:38 UTC] id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WC_REST_CRUD_Controller->update_item, WC_REST_Orders_V2_Controller->save_object, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, wc_order_fully_refunded, wc_create_refund, do_action('woocommerce_order_fully_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_fully_refunded_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Refunded_Order->trigger_full, WC_Email_Customer_Refunded_Order->trigger, WC_Email->get_content, WC_Email_Customer_Refunded_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-refunded-order.php'), do_action('woocommerce_email_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails->order_details, wc_get_template, include('/plugins/woocommerce/templates/emails/email-order-details.php'), do_action('woocommerce_email_after_order_table'), WP_Hook->do_action, WP_Hook->apply_filters, byconsolewooodt_woocommerce_email_after_order_table, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.
[11-May-2020 21:14:38 UTC] id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WC_REST_CRUD_Controller->update_item, WC_REST_Orders_V2_Controller->save_object, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, wc_order_fully_refunded, wc_create_refund, do_action('woocommerce_order_fully_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_fully_refunded_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Refunded_Order->trigger_full, WC_Email_Customer_Refunded_Order->trigger, WC_Email->get_content, WC_Email_Customer_Refunded_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-refunded-order.php'), do_action('woocommerce_email_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails->order_details, wc_get_template, include('/plugins/woocommerce/templates/emails/email-order-details.php'), do_action('woocommerce_email_after_order_table'), WP_Hook->do_action, WP_Hook->apply_filters, byconsolewooodt_woocommerce_email_after_order_table, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.
[11-May-2020 21:14:38 UTC] ID was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WC_REST_CRUD_Controller->update_item, WC_REST_Orders_V2_Controller->save_object, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, wc_order_fully_refunded, wc_create_refund, do_action('woocommerce_order_fully_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_fully_refunded_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Refunded_Order->trigger_full, WC_Email_Customer_Refunded_Order->trigger, WC_Email->get_headers, apply_filters('woocommerce_email_headers'), WP_Hook->apply_filters, byconsolewooodt_custom_wooemail_headers, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.
[12-May-2020 02:34:23 UTC] Successfully loaded service schemas from server response. (fetch_service_schemas_from_connect_server)
[12-May-2020 09:46:15 UTC] WordPress database error Deadlock found when trying to get lock; try restarting transaction for query DELETE FROM `lqk_options` WHERE `option_name` = '_transient_jpp_headers_updated_recently' made by do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, Jetpack_Protect_Module->maybe_update_headers, Jetpack_Protect_Module->get_transient, get_transient, delete_option
[12-May-2020 09:56:44 UTC] PHP Fatal error:  Uncaught Error: Class 'WC_Points_Rewards_Manager' not found in /home/customer/www/lemarchexpress.com/public_html/wp-content/plugins/mstore-api/controllers/FlutterUser.php:722
Stack trace:
#0 /home/customer/www/lemarchexpress.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1015): FlutterUserController->get_points(Object(WP_REST_Request))
#1 /home/customer/www/lemarchexpress.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(342): WP_REST_Server->dispatch(Object(WP_REST_Request))
#2 /home/customer/www/lemarchexpress.com/public_html/wp-includes/rest-api.php(306): WP_REST_Server->serve_request('/api/flutter_us...')
#3 /home/customer/www/lemarchexpress.com/public_html/wp-includes/class-wp-hook.php(287): rest_api_loaded(Object(WP))
#4 /home/customer/www/lemarchexpress.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#5 /home/customer/www/lemarchexpress.com/public_html/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#6 /home/customer/www/lemarche in /home/customer/www/lemarchexpress.com/public_html/wp-content/plugins/mstore-api/controllers/FlutterUser.php on line 722
[13-May-2020 02:03:46 UTC] Successfully loaded service schemas from server response. (fetch_service_schemas_from_connect_server)

**Comment by minhcasi** [comment]
@minhtruong315 

this could be the root cause issue from mstore-api
```
'WC_Points_Rewards_Manager' not found in /home/customer/www/lemarchexpress.com/public_html/wp-content/plugins/mstore-api/controllers/FlutterUser.php:722
```

**Comment by iamar1k92** [comment]
any updates?

**Comment by iamar1k92** [comment]
I don't want to reopen an another duplicate ticket, this problem is also there ticket #3127. I have sent the source code to kvt0012. Please also fix that.

We have also an issue when we logged into the app, Onboarding screen always show. 

And these payment gateway issues are still there,

 while points are also not working.

Fix the navigation of shop button on drawer screen. It always pops, don't navigate to home.

**Comment by iamar1k92** [comment]
@minhcasi??

It's been 14 days now, please come up with solutions, We don't have much time for this...

**Comment by minhtruong315** [comment]
Hi @iamar1k92, There is error with this link: https://lemarchexpress.com/checkout?code=b61fbefd1a422b37b31b711ebea70e89&mobile=true
But I must see the error to fix it. but your website don't show error correctly. so I can't determine the cause issue.
I also can't access to your host to see log file. I don't know how to fix your issue. on our website, it's working well.

**Comment by iamar1k92** [comment]
i have resubmitted the ftp login details, be try it out.

Otherwise i have attached the latest log file. here and on email as well


[debug.log](https://github.com/inspireui/support/files/4643330/debug.log)

**Comment by minhtruong315** [comment]
Hi  @iamar1k92 I can access to your host via ftp. but when I try to open this link: https://lemarchexpress.com/checkout?code=b61fbefd1a422b37b31b711ebea70e89&mobile=true
and check debug.log file. it's empty. can u help me check log when run above link?

**Comment by minhtruong315** [comment]
Hi @iamar1k92 I tried to delete MStore  Api plugin on your website. but when open the link: https://lemarchexpress.com/checkout?code=b61fbefd1a422b37b31b711ebea70e89&mobile=true
it still load MStore Api plugin code. Do you know that problem?

**Comment by minhtruong315** [comment]
As this issue is cause by the conflict with the existing extension from your website, we have tried our best but could not find out the root cause, would you mind to try with the fresh installing from Opencart ?
It's possible to process refund if you could not resolve this issue, thank you for your time

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by iamar1k92** [comment]
Well, there is another issue with the app, it get stuck for minutes on release mode.

**Comment by shikhardb** [comment]
> [wp-config.txt](https://github.com/inspireui/support/files/4620740/wp-config.txt)
> this is the wp-config.php file after enable the debug mode.

Can you please remove this comment? The `wp-config` file is openly linked here.
