### ISSUE TITLE
NoSuchMethodError was thrown building OnBoardScreen(dirty, state:

### ISSUE THREAD

**Issue by titicelv** [inspireui/support#3335]
Step 1 (require): detail issues and screenshots

I have successfully launched demo Flutter app which is connected to Your demo siet. After that i changed params to my website and was trying to get it work in simulation. 
I got https://prnt.sc/skw77k

This is all log:

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\MMarch\.android\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\MMarch\.android\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\MMarch\.android\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.5\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\MMarch\.android\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.9+1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Flutter is taking longer than expected to report its views. Still trying...
I/luxstore.vendo(12771): The ClassLoaderContext is a special shared library.
Debug service listening on ws://127.0.0.1:49445/CGJ7D91hGjs=/ws
Syncing files to device Android SDK built for x86...
I/chatty  (12771): uid=10135(com.inspireui.fluxstore.vendor) identical 1 line
I/luxstore.vendo(12771): The ClassLoaderContext is a special shared library.
I/DynamiteModule(12771): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:21001
I/DynamiteModule(12771): Selected remote version of com.google.android.gms.ads.dynamite, version >= 21001
D/DynamitePackage(12771): Instantiated singleton DynamitePackage.
D/DynamitePackage(12771): Instantiating com.google.android.gms.ads.reward.ChimeraRewardedVideoAdCreatorImpl
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
I/WebViewFactory(12771): Loading com.google.android.webview version 74.0.3729.185 (code 373018518)
I/luxstore.vendo(12771): The ClassLoaderContext is a special shared library.
I/luxstore.vendo(12771): The ClassLoaderContext is a special shared library.
I/cr_LibraryLoader(12771): Time to load native libraries: 32 ms (timestamps 9946-9978)
I/chromium(12771): [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(12771): Expected native library version number "74.0.3729.185", actual native library version number "74.0.3729.185"
W/cr_ChildProcLH(12771): Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
I/cr_BrowserStartup(12771): Initializing chromium process, singleProcess=false
W/luxstore.vendo(12771): Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (greylist, reflection, allowed)
E/chromium(12771): [ERROR:filesystem_posix.cc(89)] stat /data/user/0/com.inspireui.fluxstore.vendor/cache/WebView/Crashpad: No such file or directory (2)
E/chromium(12771): [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/com.inspireui.fluxstore.vendor/cache/WebView/Crashpad: No such file or directory (2)
I/FA      (12771): Tag Manager is not found and thus will not be used
W/luxstore.vendo(12771): Long monitor contention with owner pool-5-thread-1 (12814) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(BinderProxy.java:-2) waiters=0 in java.util.Set com.facebook.appevents.AppEventCollection.keySet() for 18.100s
W/luxstore.vendo(12771): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
W/AnalyticsUserIDStore(12771): initStore should have been called before calling setUserID
W/AnalyticsUserIDStore(12771): initStore should have been called before calling setUserID
D/HostConnection(12771): HostConnection::get() New Host Connection established 0xd8260960, tid 12821
D/HostConnection(12771): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
W/OpenGLRenderer(12771): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation(12771): eglCreateContext: 0xd821ac00: maj 2 min 0 rcv 2
D/HostConnection(12771): HostConnection::get() New Host Connection established 0xd8260370, tid 12843
D/HostConnection(12771): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
W/luxstore.vendo(12771): Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
D/EGL_emulation(12771): eglMakeCurrent: 0xd821ac00: ver 2 0 (tinfo 0xbeb4c840)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/luxstore.vendo(12771): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
D/EGL_emulation(12771): eglCreateContext: 0xbebd1060: maj 2 min 0 rcv 2
W/Gralloc3(12771): mapper 3.x is not supported
D/HostConnection(12771): createUnique: call
D/HostConnection(12771): createUnique: call
D/HostConnection(12771): HostConnection::get() New Host Connection established 0xd8264ba0, tid 12821
D/HostConnection(12771): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/eglCodecCommon(12771): allocate: Ask for block of size 0x1000
D/eglCodecCommon(12771): allocate: ioctl allocate returned offset 0x3ff01e000 size 0x2000
D/HostConnection(12771): HostConnection::get() New Host Connection established 0xc0895270, tid 12843
D/HostConnection(12771): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/EGL_emulation(12771): eglMakeCurrent: 0xbebd1060: ver 2 0 (tinfo 0xd820f950)
I/luxstore.vendo(12771): Background concurrent copying GC freed 29665(1697KB) AllocSpace objects, 13(1268KB) LOS objects, 49% free, 3385KB/6770KB, paused 872us total 624.934ms
D/EGL_emulation(12771): eglMakeCurrent: 0xd821ac00: ver 2 0 (tinfo 0xbeb4c840)
I/OpenGLRenderer(12771): Davey! duration=3159ms; Flags=1, IntendedVsync=42931110535006, Vsync=42931310534998, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=42931316834100, AnimationStart=42931317062400, PerformTraversalsStart=42931317141500, DrawStart=42933536581900, SyncQueued=42933540094100, SyncStart=42933569706000, IssueDrawCommandsStart=42933571452400, SwapBuffers=42933954510100, FrameCompleted=42934299450400, DequeueBufferDuration=82690000, QueueBufferDuration=16853000, 
I/Choreographer(12771): Skipped 195 frames!  The application may be doing too much work on its main thread.
E/FlutterFcmService(12771): Fatal: failed to find callback
I/flutter (12771): [2020-05-21 07:11:47.218991Z][Fluxstore][main] ============== main.dart START ==============
D/EGL_emulation(12771): eglMakeCurrent: 0xbebd1060: ver 2 0 (tinfo 0xd820f950)
I/flutter (12771): [2020-05-21 07:11:49.138899Z][Fluxstore][AppState] initState
I/flutter (12771): [2020-05-21 07:11:49.405001Z][Fluxstore][AppState] build
I/flutter (12771): [2020-05-21 07:11:49.616391Z][Fluxstore][AppState] build Theme
I/flutter (12771): screenName /
I/flutter (12771): [2020-05-21 07:11:56.687784Z][Fluxstore][AppState] Inital Data
I/flutter (12771): [2020-05-21 07:11:56.781868Z][Fluxstore][Services] setAppConfig: --> woo <--
I/flutter (12771): [2020-05-21 07:11:56.998355Z][Fluxstore][AppState] init mobile modules ..
I/flutter (12771): [2020-05-21 07:11:57.104908Z][Fluxstore][AppState] register modules .. DONE
I/flutter (12771): [2020-05-21 07:11:57.323759Z][Fluxstore][AppState] Init Data Finish
D/SharedPreferencesImpl(12771): Time required to fsync /data/user/0/com.inspireui.fluxstore.vendor/shared_prefs/com.google.android.gms.measurement.prefs.xml: [<1: 0, <2: 0, <4: 0, <8: 0, <16: 6, <32: 3, <64: 0, <128: 0, <256: 2, <512: 0, <1024: 0, <2048: 1, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
I/flutter (12771): [2020-05-21 07:12:00.409043Z][Fluxstore][AppState] build Theme
I/flutter (12771): [2020-05-21 07:12:03.060707Z][Fluxstore][Category] getCategories
I/flutter (12771): getFilterTags: NoSuchMethodError: The method 'getFilterTags' was called on null.
I/flutter (12771): Receiver: null
I/flutter (12771): Tried calling: getFilterTags()
I/flutter (12771): getFilterAttributes: NoSuchMethodError: The method 'getFilterAttributes' was called on null.
I/flutter (12771): Receiver: null
I/flutter (12771): Tried calling: getFilterAttributes()
I/flutter (12771): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (12771): #1      Services.getCategories (package:fstore/services/index.dart:200:23)
I/flutter (12771): #2      CategoryModel.getCategories (package:fstore/models/category/category_model.dart:21:35)
I/flutter (12771): #3      _AppInitState.loadInitData.<anonymous closure> (package:fstore/app_init.dart:70:16)
I/flutter (12771): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:318:39)
I/flutter (12771): #5      _rootRun (dart:async/zone.dart:1180:38)
I/flutter (12771): #6      _CustomZone.run (dart:async/zone.dart:1077:19)
I/flutter (12771): #7      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
I/flutter (12771): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
I/flutter (12771): #9      _rootRun (dart:async/zone.dart:1184:13)
I/flutter (12771): #10     _CustomZone.run (dart:async/zone.dart:1077:19)
I/flutter (12771): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
I/flutter (12771): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
I/flutter (12771): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
I/flutter (12771): #14     _Time
I/flutter (12771): [2020-05-21 07:12:03.516670Z][Fluxstore][MyConnectivity] online
I/flutter (12771): [2020-05-21 07:12:03.594590Z][Fluxstore][App] internet issue change: {ConnectivityResult.wifi: true}
I/flutter (12771): [2020-05-21 07:12:03.662643Z][Fluxstore][MyConnectivity] online
I/flutter (12771): [2020-05-21 07:12:03.663276Z][Fluxstore][App] internet issue change: {ConnectivityResult.wifi: true}
I/OpenGLRenderer(12771): Davey! duration=778ms; Flags=0, IntendedVsync=42958710635702, Vsync=42958710635702, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=42958713437400, AnimationStart=42958713494900, PerformTraversalsStart=42958765187500, DrawStart=42958765539700, SyncQueued=42958765625200, SyncStart=42958766442500, IssueDrawCommandsStart=42958766631700, SwapBuffers=42958768170200, FrameCompleted=42959490437900, DequeueBufferDuration=303000, QueueBufferDuration=10154000, 
I/Choreographer(12771): Skipped 34 frames!  The application may be doing too much work on its main thread.
I/flutter (12771): screenName null
I/flutter (12771): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12771): The following NoSuchMethodError was thrown building OnBoardScreen(dirty, state:
I/flutter (12771): _OnBoardScreenState#0eac3):
I/flutter (12771): The method '[]' was called on null.
I/flutter (12771): Receiver: null
I/flutter (12771): Tried calling: []("OnBoarding")
I/flutter (12771): 
I/flutter (12771): The relevant error-causing widget was:
I/flutter (12771):   OnBoardScreen file:///C:/Users/MMarch/Desktop/TiTiCe/APP/ven/flu/source/lib/app_init.dart:89:45
I/flutter (12771): 
I/flutter (12771): When the exception was thrown, this was the stack:
I/flutter (12771): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (12771): #1      _OnBoardScreenState.build (package:fstore/screens/home/onboard_screen.dart:180:40)
I/flutter (12771): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
I/flutter (12771): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (12771): #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (12771): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (12771): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (12771): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
I/flutter (12771): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (12771): ...     Normal element mounting (95 frames)
I/flutter (12771): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (12771): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (12771): #105    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5580:32)
I/flutter (12771): #106    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5957:17)
I/flutter (12771): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (12771): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (12771): #109    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (12771): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (12771): #111    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter (12771): #112    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
I/flutter (12771): #113    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (12771): #114    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (12771): #115    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (12771): #116    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (12771): #120    _invoke (dart:ui/hooks.dart:261:10)
I/flutter (12771): #121    _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (12771): (elided 3 frames from dart:async)
I/flutter (12771): 
I/flutter (12771): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (12771): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (12771): <!doctype html>
E/flutter (12771): ^
E/flutter (12771): 
E/flutter (12771): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
E/flutter (12771): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1261:9)
E/flutter (12771): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:926:22)
E/flutter (12771): #3      _parseJson (dart:convert-patch/convert_patch.dart:31:10)
E/flutter (12771): #4      JsonDecoder.convert (dart:convert/json.dart:505:36)
E/flutter (12771): #5      JsonCodec.decode (dart:convert/json.dart:153:41)
E/flutter (12771): #6      jsonDecode (dart:convert/json.dart:96:10)
E/flutter (12771): #7      Blog.getBlogs (package:fstore/models/blogs/blog.dart:85:12)
E/flutter (12771): <asynchronous suspension>
E/flutter (12771): #8      BlogModel.getBlogs (package:fstore/models/blogs/blog.dart:20:29)
E/flutter (12771): #9      _AppInitState.loadInitData.<anonymous closure> (package:fstore/app_init.dart:72:58)
E/flutter (12771): #10     new Future.delayed.<anonymous closure> (dart:async/future.dart:318:39)
E/flutter (12771): #11     _rootRun (dart:async/zone.dart:1180:38)
E/flutter (12771): #12     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (12771): #13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (12771): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (12771): #15     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (12771): #16     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (12771): #17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (12771): #18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (12771): #19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (12771): #20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (12771): #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (12771): 
`

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by titicelv** [comment]
I have sorted it out by deleting build directory and started from scratch
