### ISSUE TITLE
appbundle build issue

### ISSUE THREAD

**Issue by konnect1989** [inspireui/support#3796]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Hi
We are getting following error while executing flutter build appbundle

1. 
lib/menu.dart:74:21: Error: Expected ':' before this.
                    title: "Donate Now",
                    ^^^^^
lib/menu.dart:74:26: Error: Expected ')' before this.
                    title: "Donate Now",
                         ^
lib/menu.dart:74:21: Error: The getter 'title' isn't defined for the class '_MenuBarState'.
 - '_MenuBarState' is from 'package:fstore/menu.dart' ('lib/menu.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'title'.
                    title: "Donate Now",

Code in menu.dart having issue is : 

` case 'web':
        {
          String locale = Provider.of<AppModel>(context, listen: false).locale;
          return ListTile(
            leading: const Icon(
              Icons.web,
              size: 20,
            ),
            title: Text(S.of(context).webView),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => WebView(
                    url: locale == 'en'
                        ? "google.com"
                    title: "Donate Now",
                  ),
                ),
              );
            },
          );
        }`

2. /F:/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
/F:/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'F:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'F:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

+ Product & version: Fluxnews latest
+ Flutter (or React Native) version:  latest
+ Testing Device/Simulator:  not able to build apk/app bundle
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@konnect1989 - could you try to clean up the cache to fix the issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Also, make sure to run the `flutter pub get` to update the library.

Thank you!

**Comment by konnect1989** [comment]
Hello already did

Same issue



.
>

**Comment by konnect1989** [comment]
cleaned, ran gradelew.bat, and issue perisists. its saying code issue as you can see from below message. 

Compiler message:
lib/menu.dart:74:21: Error: Expected ':' before this.
                    title: "Donate Now",
                    ^^^^^
lib/menu.dart:74:26: Error: Expected ')' before this.
                    title: "Donate Now",
                         ^
lib/menu.dart:74:21: Error: The getter 'title' isn't defined for the class '_MenuBarState'.
 - '_MenuBarState' is from 'package:fstore/menu.dart' ('lib/menu.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'title'.
                    title: "Donate Now",
                    ^^^^^
/F:/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
/F:/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'F:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'F:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 9s

**Comment by minhcasi** [comment]
- could you share the whole screenshot issues from your Android Studio
- try to send us the result from `flutter doctor`
- could you confirm if you can able run this Test Drive example - https://flutter.dev/docs/get-started/test-drive?tab=vscode ?

**Comment by konnect1989** [comment]
Hello
after we change title : "Donate Now", to title: S.of(context).webView, , first part of error disappears.

but then new errors are there as below : 

--> Errors are pointing towards a coding issue, instead of issue with my setup. Pls do not send me round and round, as I do not have that much time to spend only to realise that app doesn't work. It has been 3 days to setup an app which according to your documentation should not have taken more than 3 hours. If you know that your code doesn't work, then refund, or if it works, then send me the working code from which you have generated apk bundle previously, where I can replace the configuration changes I have made following your documentation and build the app. 
--> There is clearly an issue also with the title of Menu item, as below error log of "flutter build appbundle" is saying . When I use only title as was suggested on chat by your documentation person, it doesn't work. While when I am using code, error disappears but that doesn't solve the problem. 

Pls guide on how to generate app bundle in a single reply, with perfect guide, so that I do not have to wait another 24 hours for this. 

moreover my test flutter app is building and working normally. 


![flutter fluxnews screen android studio](https://user-images.githubusercontent.com/67134072/85196393-aac62500-b2f7-11ea-92f9-3d3b8c914cdb.png)
![fluuter doctor](https://user-images.githubusercontent.com/67134072/85196395-abf75200-b2f7-11ea-87db-9ffcca8ce2ba.png)

=============
new log, after replacing Donate Now title with code, as was already present in your script

Compiler message:
lib/menu.dart:59:9: Error: Expected ';' after this.
        import 'widgets/webview.dart';
        ^^^^^^
lib/menu.dart:59:9: Error: The getter 'import' isn't defined for the class '_MenuBarState'.
 - '_MenuBarState' is from 'package:fstore/menu.dart' ('lib/menu.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'import'.
        import 'widgets/webview.dart';
        ^^^^^^
/F:/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
/F:/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'F:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'F:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 32s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                       283.5s (!)
Gradle task bundleRelease failed with exit code 1

**Comment by konnect1989** [comment]
also I have below questions related to the code, kindly answer


1. cannot find login_sms_constants.dart in fluxnews , so not able to change default country code

2. how to remove other two languages? we want only english and hindi in the app


3.  I saw option to enable point system, which I have put as "true". which point system is being used? mycred or gamipress? will it reward people on reading posts? will it reward people on watching reward ads? how to configure it? how will user be able to see his points? is there any leaderboard?

4. We want to create a new language - Hindi, we have created corresponding config_hi.json file, but how to connect it to the app? Also how to remove other two languages? we want only english and hindi in the app. Pls send detailed step by step instruction and code to place in files. the documentation on translation is unclear, kindly guide with step by step instruction.

  5. How to create about us or contact us pages within the app? You have pageviews, and it is using a code to call pageID. is that wordpress page ID? 

 7. Can we enable tawk.to chat instead of intercom in the app?

8. Admob rewards ads, how to award points to users who see ads? which point system will be used?

9. Admob native ads is not supported? I see only banner, interstitial and reward ads in the config.dart file.

  10. When a user opens a category, we want first post to be the latest post, and then below that, a list of all posts in that category, starting from first post in the category (not the latest one). How to configure it? pls send changes in code for the same


Pls answer our queries, so that we can make required changes, create and upload the app. 
thank you

**Comment by minhcasi** [comment]
@konnect1989 - this is long questions need more checking, I've assigned to one of my team and get back you on Tuesday - thank you!

**Comment by konnect1989** [comment]
If you can first solve the build issue, thats most important.

Rest of the questions you can do on tuesday as they are mostly feature
related.

But build not generating, is a code issue.

Pls send source code from which you are able to generate app bundle, so
that I can replace common files and images in that, and generate our app
bundle

Thanks

**Comment by dttrung26** [comment]
Hi @konnect1989 , 
I'm working on your issue and will get you back as soon as possible. 
By the way, could you send me your modified file /lib/menu.dart file for checking? I need to take a clear look at that. 
Many thanks!

**Comment by dttrung26** [comment]
Hey @konnect1989 , 
- For the first issue in title: "Donate now", please replace menu.dart in your /lib/menu.dart 
- For rate_my_app plugin issue, please go to pubspec.yaml and upgrade `rate_my_app: ^0.6.1+6`
- Moreover, as I checked, your config_en.json file located at https://divinemahaguru.com/app/config_en.json' is currently wrongly formatted (unnessecary

**Comment by konnect1989** [comment]
thank you for your response
where is the attached file for config? probably you forgot that?

**Comment by konnect1989** [comment]
If I want to create a webview and pageview link of Menu item "Google", going to "google.com", what code should I use? I followed the documentation, but thats giving error.
what changes need to be made in below code?
case 'web':
        {
          String locale = Provider.of<AppModel>(context, listen: false).locale;
          return ListTile(
            leading: const Icon(
              Icons.web,
              size: 20,
            ),
            title: Text(S.of(context).webView),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => WebView(
                    url: locale == 'en'
                        ? "https://www.google.com"
                        : "https://facebook.com",
                    title: S.of(context).webView.toString(),
                  ),
                ),
              );
            },
          );
        }

**Comment by konnect1989** [comment]
also pls remove screenshot and our URL from the ticket for privacy concerns.

**Comment by dttrung26** [comment]
Hi @konnect1989 , 
here come your solutions: 
+ In order to change default phone code, please go to `kAdvanceConfig` located at `lib/common/config.dart` and add a new pair value like this: `  "DefaultPhoneISOCode": "+44" `, don't forget to replace your desired default phone code. 
+ In order to remove unwanted languages, please go to /lib/common/tools.dart and comment out / delete those languages you don't want like.
<img width="711" alt="Screen Shot 2020-06-24 at 09 55 34" src="https://user-images.githubusercontent.com/32586676/85493314-dcddcc80-b600-11ea-9029-d7913ebe712a.png">
+  For those questions related to Ads, current supported Ads types are:   googleBanner, googleInterstitial, googleReward, facebookBanner, facebookInterstitial, facebookNative, facebookNativeBanner. 
+ Those issues related to Customization services are: Config `RewardPoint`, config `CategoriesScreen`, integrate with tawk.to. For those concerns, please contact support@inpireui.com and declare your requests, InspireUI supporters will contact you and discuss estimated time and cost.
+ Yes, in PageView and WebView widget, pageId parameter is Wordpress Page ID. 
+ In order to add a new language to FluxNews, please follow this docs: https://docs.inspireui.com/fluxnews/multi-language/. There's a example code in which we config existing languages already. You can take that as references. 

```
case 'web':
{
String locale = Provider.of(context, listen: false).locale;
return ListTile(
leading: const Icon(
Icons.web,
size: 20,
),
title: Text(S.of(context).webView),
onTap: () {
Navigator.push(
context,
MaterialPageRoute(
builder: (context) => WebView(
url: locale == 'en'
? "https://www.google.com"
: "https://facebook.com",
title: S.of(context).webView.toString(),
),
),
);
},
);
}
```
- I've realized there's lack of documents in phone code and languages configurations. We'll be working on that soon. Stay tuned. 

Let me know if you still have any questions.
Best!

**Comment by konnect1989** [comment]
Hi
I have added a new strings_hi.arb file
install i18n plugin 
in tools.dart, I commented out all lines of code for Vietnamese and Arabian language and added following :

`{`
        "name": context != null ? S.of(context).hindi : "Hindi",
        "icon": "assets/images/country/in.png",
        "code": "hi",
        "text": "Hindi",
        "storeViewCode": ""
      `},`

then I have added below to l10n.dart
  /// `Indian`
  String get hindi {
    return Intl.message(
      'Hindi',
      name: 'hindi',
      desc: '',
      args: [],
    );
  }

I have specified hindi: "Hindi", in both strings.arb and strings_hi.arb 

what is wrong here, and how to fix it? build is again failing. 


Also how to modify the contents of Settings-->Contact, Settings-->Rate the app box that appears? its text is not there in language file. How to change the image thats appearing in settings screen?



getting below error while running flutter build apk

lib/common/tools.dart:343:49: Error: The getter 'hindi' isn't defined for the class 'S'.
 - 'S' is from 'package:fstore/generated/l10n.dart' ('lib/generated/l10n.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hindi'.
        "name": context != null ? S.of(context).hindi : "Hindi",
                                                ^^^^^

**Comment by dttrung26** [comment]
Hi @konnect1989 ,
please try to install Flutter Intl plugin instead of i18n and try again to see if it works. 
Don't forget to add those lines at the same level as name, description, version, ... at pubspec.yaml file
```
flutter_intl:
  enabled: true
```

**Comment by konnect1989** [comment]
that is already enabled. still there is above error.

what am I missing here? Is my code and its placements right?

**Comment by dttrung26** [comment]
Hi @konnect1989 , 
kindly leave me error log here for checking, many thanks!

**Comment by konnect1989** [comment]
I have already created strings_hi.arb, translated it and installed i18n
plugin. That part is done.

Pls tell me next exact steps that need to be followed to add a new language
so that users can choose it from settings screen.


Also tell me steps to completely remove (not just comment out), Vietnamese
and arabian language. We don't want them in the code, as they are not our
target audience as of now.

Thanks

**Comment by konnect1989** [comment]
along with above issue, when we are trying to generate an apk instead of appbundle (after removing hindi language settings), with flutter build apk, we are getting below error log

pls tell steps on how to fix the language issue as in previous reply, and also what is causing below issue while building apk? aab was built properly, but apk is not building

===========

F:\flutter\bin\flutter.bat --no-color build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...                        

AAPT2 aapt2-3.5.0-5435860-windows Daemon #4: Unexpected standard output: Ready
AAPT2 aapt2-3.5.0-5435860-windows Daemon #5: Unexpected standard output: Ready
AAPT2 aapt2-3.5.0-5435860-windows Daemon #7: Unexpected standard output: Ready
AAPT2 aapt2-3.5.0-5435860-windows Daemon #6: Unexpected standard output: Ready

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apple_sign_in:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > AAPT2 aapt2-3.5.0-5435860-windows Daemon #0: Daemon startup failed
     This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20m 40s

















Running Gradle task 'assembleRelease'...                         1256.5s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin apple_sign_in...
Running Gradle task 'assembleAarRelease'...                       144.4s (!)
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

> Configure project :
WARNING: The option setting 'android.enableR8=true' is experimental and unsupported.
The current default is 'false'
Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.
File C:\Users\--\.android\repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 28.0.3 in C:\Users\--\AppData\Local\Android\sdk\licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
Checking the license for package Android SDK Platform 28 in C:\Users\--\AppData\Local\Android\sdk\licenses
Warning: License for package Android SDK Platform 28 not accepted.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'apple_sign_in'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

  Using Android SDK: C:\Users\--\AppData\Local\Android\sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 10s

The plugin apple_sign_in could not be built due to the issue above.
Process finished with exit code 1

**Comment by konnect1989** [comment]
Hi
we have generated an aab, then used buildtool to extract a universal apk, apk is not running, and stuck on blank opening screen

below is the error log of main.dart run from android studio

pls help
thanks



====
Launching lib\main.dart on ONEPLUS A6010 in debug mode...
Running Gradle task 'assembleDebug'...
Note: F:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+5\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: F:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: F:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: F:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.5\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: F:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: F:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
√ Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter (21893): 
Installing build\app\outputs\apk\app.apk...
I/flutter (22475): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (22475): The following NoSuchMethodError was thrown building Consumer<AppModel>(dirty, dependencies:
I/flutter (22475): [_InheritedProviderScope<AppModel>]):
I/flutter (22475): The method '[]' was called on null.
I/flutter (22475): Receiver: null
I/flutter (22475): Tried calling: []("Setting")
I/flutter (22475): 
I/flutter (22475): The relevant error-causing widget was:
I/flutter (22475):   Consumer<AppModel> file:///F:/-/flux/source/lib/app.dart:66:14
I/flutter (22475): 
I/flutter (22475): When the exception was thrown, this was the stack:
I/flutter (22475): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (22475): #1      MyAppState.build.<anonymous closure> (package:fstore/app.dart:116:50)
I/flutter (22475): #2      Consumer.buildWithChild (package:provider/src/consumer.dart:175:19)
I/flutter (22475): #3      SingleChildStatelessWidget.build (package:nested/nested.dart:260:41)
I/flutter (22475): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
I/flutter (22475): #5      SingleChildStatelessElement.build (package:nested/nested.dart:280:18)
I/flutter (22475): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (22475): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (22475): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter (22475): #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
I/flutter (22475): #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (22475): #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (22475): #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (22475): #13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (22475): #17     _invoke (dart:ui/hooks.dart:261:10)
I/flutter (22475): #18     _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (22475): (elided 3 frames from dart:async)
I/flutter (22475): 
I/flutter (22475): ════════════════════════════════════════════════════════════════════════════════════════════════════
Debug service listening on ws://127.0.0.1:54099/T7_B7jwy4nA=/ws
Syncing files to device ONEPLUS A6010...
W/ActivityThread(22475): handleWindowVisibility: no activity for token android.os.BinderProxy@a44c45a
V/ViewRootImpl(22475): The specified message queue synchronization  barrier token has not been posted or has already been removed
D/DecorView(22475): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@b06f80a[MainActivity]
W/Choreographer(22475): Already have a pending vsync event.  There should only be one at a time.
D/OnePlusJankManager(22475):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = com.mahaguru.app/com.mahaguru.app.MainActivity--- jank level = 1
I/flutter (22475): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (22475): The following NoSuchMethodError was thrown building Consumer<AppModel>(dirty, dependencies:
I/flutter (22475): [_InheritedProviderScope<AppModel>]):
I/flutter (22475): The method '[]' was called on null.
I/flutter (22475): Receiver: null
I/flutter (22475): Tried calling: []("Setting")
I/flutter (22475): 
I/flutter (22475): The relevant error-causing widget was:
I/flutter (22475):   Consumer<AppModel> file:///F:/-/flux/source/lib/app.dart:66:14
I/flutter (22475): 
I/flutter (22475): When the exception was thrown, this was the stack:
I/flutter (22475): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (22475): #1      MyAppState.build.<anonymous closure> (package:fstore/app.dart:116:50)
I/flutter (22475): #2      Consumer.buildWithChild (package:provider/src/consumer.dart:175:19)
I/flutter (22475): #3      SingleChildStatelessWidget.build (package:nested/nested.dart:260:41)
I/flutter (22475): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
I/flutter (22475): #5      SingleChildStatelessElement.build (package:nested/nested.dart:280:18)
I/flutter (22475): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (22475): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (22475): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter (22475): #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
I/flutter (22475): #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (22475): #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (22475): #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (22475): #13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (22475): #17     _invoke (dart:ui/hooks.dart:261:10)
I/flutter (22475): #18     _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (22475): (elided 3 frames from dart:async)
I/flutter (22475): 
I/flutter (22475): ════════════════════════════════════════════════════════════════════════════════════════════════════
Malformed message
D/DecorView(22475): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@b06f80a[MainActivity]
E/OneSignal(22475): Error updating the user record because of th enull user id

**Comment by konnect1989** [comment]
Hi
it has been 10 days since we are trying to make this work now. we had a launch date 2 days ago, and we have missed it. Pls let me know clearly if this app builds and works or not? if not, pls let us know, we will look for some other solution. We wanted yours to work as we liked the application, but getting stuck with just so many issues. We solve one and another pops up.

pls help here

**Comment by dttrung26** [comment]
Hi @konnect1989 , 
here's a few tips that can help you through it: 
- Please follow this latest docs in order to configure new language: https://docs.inspireui.com/fluxstore/multi-language/ 
- In terms of existing Vietnamese and Arabic, you can just leave it there. Commenting this out won't affect your code performance, I can ensure you about that. 
- In terms of releasing your app, please follow those docs: https://docs.inspireui.com/fluxstore/delivery/, https://flutter.dev/docs/deployment/android and https://flutter.dev/docs/deployment/android. We are not responsible for the released app which already been modified. So far that's all I can help. 
Best!

**Comment by konnect1989** [comment]
Hello
we did just simple customizations as is needed for the app to function. if app is not building, what will be the use of code for us?
we have modified only the customizations that you promise that your app offers. 

and we have followed your guide already. aab generated is not working, I have provided you error log for that. 
if we are not able to release app, then our purchase becomes useless. 

pls help

**Comment by konnect1989** [comment]
We are tired of running around since last 10 days, which was job of a few hours. We went through your documentation and purchased your software only based on that, that it will be easy to configure, but it has been a tones of errors which cannot be fixed. pls cancel license and refund, we are going with wordroid for now.

**Comment by dttrung26** [comment]
Hi @konnect1989 , 
I could see your efforts on running your app. However, that's all I could help you with fixing issues. If you still need to co-operate with FluxNews, you could contact me via skype: dttrung26 and we could do some teamviewer after that. If you still insist, you could take a look at refund process here: https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund-
Happy coding!
