### ISSUE TITLE
Recently Added link not displaying

### ISSUE THREAD

**Issue by JaserJsk** [inspireui/support#3970]
**As the title says - The Recently Added link not displaying any items.**

**See the attached image.**

![Error](https://user-images.githubusercontent.com/25635376/85997598-fb313700-ba09-11ea-81a2-25e9447248fd.jpg)

**Comment by ameenbadri7** [comment]
hello, @JaserJsk  Wellcome back

it's all about pointing your `categories `to the right `category id `

could you try to use our [guide ](https://docs.inspireui.com/fluxstore/common-issues/) it will fix the issue you have?

please let us know if you still have that problem.

**Comment by JaserJsk** [comment]
> hello, @JaserJsk Wellcome back
> 
> it's all about pointing your `categories `to the right `category id `
> 
> could you try to use our [guide ](https://docs.inspireui.com/fluxstore/common-issues/) it will fix the issue you have?
> 
> please let us know if you still have that problem.

**That did NOT Help - I read all of it butdid not find a solution for it.**

**Can you be more specefic ?**

**Comment by JaserJsk** [comment]
**I also have a nother issue that I will post here.**

**Smart Chat is returning a white blank page**

**Below is the output**

D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
I/flutter (18081): screenName null
I/flutter (18081): Bad state: Failed to load https://souk.senseidev.com/wp-content/uploads/2017/06/glass-38_720x6601-medium.jpg.
I/flutter (18081): Bad state: Failed to load https://souk.senseidev.com/wp-content/uploads/2017/06/glass-40_720x660-medium.jpg.
I/flutter (18081): Bad state: Failed to load https://souk.senseidev.com/wp-content/uploads/2017/06/glass-39_720x660-medium.jpg.
I/flutter (18081): Bad state: Failed to load https://souk.senseidev.com/wp-content/uploads/2017/06/glass-26_720x6602-medium.jpg.
I/flutter (18081): Bad state: Failed to load https://souk.senseidev.com/wp-content/uploads/2017/06/glass-43_720x6601-medium.jpg.
I/flutter (18081): Bad state: Failed to load https://souk.senseidev.com/wp-content/uploads/2017/06/glass-34_720x660-medium.jpg.
I/flutter (18081): Bad state: Failed to load https://souk.senseidev.com/wp-content/uploads/2017/06/glass-42_720x6601-medium.jpg.
I/flutter (18081): Bad state: Failed to load https://souk.senseidev.com/wp-content/uploads/2017/06/glass-37_720x660-medium.jpg.
I/flutter (18081): Bad state: Failed to load https://souk.senseidev.com/wp-content/uploads/2017/06/glass-41_720x660-medium.jpg.
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
D/ViewRootImpl@85919aa[MainActivity](18081): Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 478421594112} changed=false
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
I/flutter (18081): screenName /login
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
W/ActivityThread(18081): handleWindowVisibility: no activity for token android.os.BinderProxy@44a7eb5
I/DecorView(18081): createDecorCaptionView >> DecorView@bb7abee[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/InputTransport(18081): Input channel constructed: fd=224
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): setView = DecorView@bb7abee[SignInHubActivity] TM=true MM=false
D/ViewRootImpl@85919aa[MainActivity](18081): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(18081): prepareNavigationBarInfo() DecorView@fb3151d[MainActivity]
D/InputMethodManager(18081): getNavigationBarColor() -16777216
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): dispatchAttachedToWindow
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): Relayout returned: old=[0,0][1440,2900] new=[0,0][1440,2900] result=0x7 surface={valid=true 478011490304} 
changed=true
D/mali_winsys(18081): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(18081): eglCreateWindowSurface = 0x6f4b0d2480, 0x6f4bb48010
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): MSG_RESIZED: frame=Rect(0, 0 - 1440, 2900) ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(18081): prepareNavigationBarInfo() DecorView@bb7abee[SignInHubActivity]
D/InputMethodManager(18081): getNavigationBarColor() -855310
D/InputMethodManager(18081): prepareNavigationBarInfo() DecorView@bb7abee[SignInHubActivity]
D/InputMethodManager(18081): getNavigationBarColor() -855310
V/InputMethodManager(18081): Starting input: tba=com.senseidev.souk ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(18081): startInputInner - Id : 0
I/InputMethodManager(18081): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(18081): Input channel constructed: fd=225
D/InputTransport(18081): Input channel destroyed: fd=112
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(18081): prepareNavigationBarInfo() DecorView@bb7abee[SignInHubActivity]
D/InputMethodManager(18081): getNavigationBarColor() -855310
D/InputTransport(18081): Input channel destroyed: fd=225
I/System.out(18081): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(18081): (HTTPLog)-Static: isSBSettingEnabled false
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): setWindowStopped(false) old=false
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(18081): prepareNavigationBarInfo() DecorView@bb7abee[SignInHubActivity]
D/InputMethodManager(18081): getNavigationBarColor() -855310
D/InputMethodManager(18081): prepareNavigationBarInfo() DecorView@bb7abee[SignInHubActivity]
D/InputMethodManager(18081): getNavigationBarColor() -855310
V/InputMethodManager(18081): Starting input: tba=com.senseidev.souk ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(18081): startInputInner - Id : 0
I/InputMethodManager(18081): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(18081): Input channel constructed: fd=225
D/ViewRootImpl@85919aa[MainActivity](18081): setWindowStopped(false) old=false
D/ViewRootImpl@85919aa[MainActivity](18081): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(18081): prepareNavigationBarInfo() DecorView@fb3151d[MainActivity]
D/InputMethodManager(18081): getNavigationBarColor() -16777216
D/InputMethodManager(18081): prepareNavigationBarInfo() DecorView@fb3151d[MainActivity]
D/InputMethodManager(18081): getNavigationBarColor() -16777216
V/InputMethodManager(18081): Starting input: tba=com.senseidev.souk ic=null mNaviBarColor -16777216 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(18081): startInputInner - Id : 0
I/InputMethodManager(18081): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(18081): Input channel constructed: fd=226
D/InputTransport(18081): Input channel destroyed: fd=225
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(18081): prepareNavigationBarInfo() DecorView@bb7abee[SignInHubActivity]
D/InputMethodManager(18081): getNavigationBarColor() -855310
D/ViewRootImpl@85919aa[MainActivity](18081): Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 478421594112} changed=false
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): setWindowStopped(true) old=false
W/libEGL  (18081): EGLNativeWindowType 0x6f4bb48010 disconnect failed
D/OpenGLRenderer(18081): eglDestroySurface = 0x6f4b0d2480, 0x6f4bb48000
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): dispatchDetachedFromWindow
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): Surface release. android.view.ViewRootImpl.doDie:7979 android.view.ViewRootImpl.die:7947 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.ActivityThread.handleDestroyActivity:4753 android.app.servertransaction.DestroyActivityItem.execute:39 android.app.servertransaction.TransactionExecutor.executeLifecycleState:145
D/InputTransport(18081): Input channel destroyed: fd=224
D/ViewRootImpl@847e8a1[SignInHubActivity](18081): Surface release. android.view.ViewRootImpl$ViewRootHandler.handleMessage:4825 android.os.Handler.dispatchMessage:106
I/flutter (18081): {msg: user logged in., wp_user_id: 34, cookie: Dalal.Samak|1714434304|hE9H16aNwKkegmcJ93yG0OQZ2JP2TDtjmzKy4PyWJy6|208e709d3fa0b5f80b30b6ad495bede4ca8b6cbfa78d22748205b304e093faa8, user_login: Dalal.Samak, user: {id: 34, username: Dalal.Samak, nicename: dalal-samak, email: dalal.samak.sk@gmail.com, url: , registered: 2020-06-29 19:36:37, displayname: Dalal Samak, firstname: Dalal Samak, lastname: , nickname: Dalal.Samak, description: , capabilities: {seller: true}, role: [seller], avatar: https://secure.gravatar.com/avatar/54ad3ba0a57960d03c1b688065eefc39?s=96&d=mm&r=g}}
I/flutter (18081): https://secure.gravatar.com/avatar/54ad3ba0a57960d03c1b688065eefc39?s=96&d=mm&r=g
I/flutter (18081): token: euPFx0z7uFY:APA91bG5sr_QstSx7ZChXsw2szzUmP2OZH6Hoz404G_XJrl43SDLyIUTz3bdyRygoIiDo6dlCxZsDO5aDPgRTErvHcKPCRyWFZVEsW-xKsyuFNU9Nf2FO3pQ_wQeYjtmvI5GxpyZjn2w
D/ConnectivityManager(18081): requestNetwork; CallingUid : 10465, CallingPid : 18081
W/DynamiteModule(18081): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(18081): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(18081): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
V/NativeCrypto(18081): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
W/.senseidev.sou(18081): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
W/.senseidev.sou(18081): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
I/ProviderInstaller(18081): Installed default security provider GmsCore_OpenSSL
D/ConnectivityManager(18081): requestNetwork; CallingUid : 10465, CallingPid : 18081
W/.senseidev.sou(18081): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/.senseidev.sou(18081): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/.senseidev.sou(18081): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/.senseidev.sou(18081): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/.senseidev.sou(18081): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
W/.senseidev.sou(18081): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/.senseidev.sou(18081): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
W/Firestore(18081): (21.3.0) [Firestore]: Write failed at users/dalal.samak.sk@gmail.com: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
I/flutter (18081): PlatformException(Error performing setData, PERMISSION_DENIED: Missing or insufficient permissions., null)
I/flutter (18081): screenName /home
I/flutter (18081): [2020-06-29 23:45:05.082362Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
D/ViewRootImpl@85919aa[MainActivity](18081): Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 478421594112} changed=false
I/flutter (18081): [2020-06-29 23:45:05.401928Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
I/flutter (18081): screenName null
I/flutter (18081): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (18081): The following assertion was thrown during performLayout():
I/flutter (18081): BoxConstraints forces an infinite width and infinite height.
I/flutter (18081): These invalid constraints were provided to RenderIgnorePointer's layout() function by the following
I/flutter (18081): function, which probably computed the invalid constraints in question:
I/flutter (18081):   RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:491:11)
I/flutter (18081): The offending constraints were:
I/flutter (18081):   BoxConstraints(biggest)
I/flutter (18081):
I/flutter (18081): The relevant error-causing widget was:
I/flutter (18081):   MaterialApp file:///D:/Accounts/Jaser/GitHub/Middle-East-Souk/me_souk_app/lib/app.dart:196:20
I/flutter (18081):
I/flutter (18081): When the exception was thrown, this was the stack:
I/flutter (18081): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:519:9)
I/flutter (18081): #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:559:21)
I/flutter (18081): #2      _Closure.call (dart:core-patch/function.dart)
I/flutter (18081): #3      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:567:6)
I/flutter (18081): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1672:24)
I/flutter (18081): #5      RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:491:11)
I/flutter (18081): #6      _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:705:42)
I/flutter (18081): #7      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (18081): #8      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
I/flutter (18081): #9      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
I/flutter (18081): #10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
I/flutter (18081): #11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (18081): #12     _Closure.call (dart:core-patch/function.dart)
I/flutter (18081): #13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1115:15)
I/flutter (18081): #14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1054:9)
I/flutter (18081): #15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:970:5)
I/flutter (18081): #19     _invoke (dart:ui/hooks.dart:253:10)
I/flutter (18081): #20     _drawFrame (dart:ui/hooks.dart:211:3)
I/flutter (18081): (elided 3 frames from dart:async)
I/flutter (18081):
I/flutter (18081): The following RenderObject was being processed when the exception was fired: _RenderTheatre#da94e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (18081):   needs compositing
I/flutter (18081):   creator: _Theatre ← Overlay-[LabeledGlobalKey<OverlayState>#07468] ← _FocusMarker ← Semantics ←
I/flutter (18081):     FocusScope ← AbsorbPointer ← _PointerListener ← Listener ← HeroControllerScope ←
I/flutter (18081):     Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#a609f] ← IconTheme ← IconTheme ← ⋯
I/flutter (18081):   parentData: <none> (can use size)
I/flutter (18081):   constraints: BoxConstraints(w=360.0, h=725.0)
I/flutter (18081):   size: Size(360.0, 725.0)
I/flutter (18081):   skipCount: 1
I/flutter (18081):   textDirection: ltr
I/flutter (18081): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (18081):     onstage 1: RenderIgnorePointer#a5207
I/flutter (18081):       child: RenderBlockSemantics#3f94b
I/flutter (18081):         child: RenderExcludeSemantics#cfb83
I/flutter (18081):           child: RenderSemanticsGestureHandler#ac398
I/flutter (18081):             child: RenderPointerListener#e8dcb
I/flutter (18081):     onstage 2: RenderSemanticsAnnotations#72e17
I/flutter (18081):       child: RenderOffstage#35424
I/flutter (18081):         child: RenderSemanticsAnnotations#914b6
I/flutter (18081):           child: RenderRepaintBoundary#bb98f
I/flutter (18081):             child: RenderFractionalTranslation#14be9
I/flutter (18081):     onstage 3: RenderIgnorePointer#bc5d6
I/flutter (18081):       child: RenderBlockSemantics#0a0a4
I/flutter (18081):         child: RenderExcludeSemantics#94e28
I/flutter (18081):           child: RenderSemanticsGestureHandler#b7bef
I/flutter (18081):             child: RenderPointerListener#1a3a2
I/flutter (18081):     onstage 4: RenderSemanticsAnnotations#39189 NEEDS-PAINT
I/flutter (18081):       child: RenderOffstage#d2117 NEEDS-PAINT
I/flutter (18081):         child: RenderSemanticsAnnotations#8c965 NEEDS-PAINT
I/flutter (18081):           child: RenderRepaintBoundary#c6444 NEEDS-PAINT
I/flutter (18081):             child: RenderFractionalTranslation#5d3f8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (18081):     onstage 5: RenderIgnorePointer#a5d92 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (18081):       child: RenderRepaintBoundary#31e4c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (18081):         child: RenderOpacity#b80fa NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (18081):           child: RenderSemanticsAnnotations#39fc0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (18081):             child: _RenderInputPadding#0595e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (18081):     ...(descendants list truncated after 25 lines)
I/flutter (18081): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 0
D/ViewRootImpl@85919aa[MainActivity](18081): ViewPostIme pointer 1
I/flutter (18081): screenName null
W/Firestore(18081): (21.3.0) [Firestore]: Listen for Query(chatRooms/-dalal.samak.sk@gmail.com) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
I/flutter (18081): PlatformException(Error performing get, PERMISSION_DENIED: Missing or insufficient permissions., null)

**Comment by ameenbadri7** [comment]
Ok please send your `lib/common` and `lib/config` folders 
And creat a temporary admin user in your site and send the user and the password to our private via email minh@inspireui.com and declare this ticket url inside the message.  I will help you with that.

THANK YOU

**Comment by minhcasi** [comment]
@JaserJsk - pls help to continuous your comment on this ticket #3852
