### ISSUE TITLE
Can not build CEStore

### ISSUE THREAD

**Issue by hdecode** [inspireui/support#4287]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Can not build the source code 
1. I have follow the video to build source code: npm install
2. The first error, which can not install grpc, I pass it by `npm install grpc -g`
3. The second error, do not find @Profiler and I remove it from package json
4. Now I run expo start --android and it fails

\Projects\bs-mobile2\CeStore-1.3.0\Source\mobile-full\node_modules\metro-config\src\defaults\blacklist.js:38
  return new RegExp(
         ^

SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (E:\Projects\bs-mobile2\CeStore-1.3.0\Source\mobile-full\node_modules\metro-config\src\defaults\blacklist.js:38:10)
    at getBlacklistRE (E:\Projects\bs-mobile2\CeStore-1.3.0\Source\mobile-full\node_modules\react-native\local-cli\util\Config.js:56:8)
    at Object.<anonymous> (E:\Projects\bs-mobile2\CeStore-1.3.0\Source\mobile-full\node_modules\react-native\local-cli\util\Config.js:71:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._compile (E:\Projects\bs-mobile2\CeStore-1.3.0\Source\mobile-full\node_modules\pirates\lib\index.js:99:24)    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .js] (E:\Projects\bs-mobile2\CeStore-1.3.0\Source\mobile-full\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (C:\@expo\xdl@57.9.24\src\Project.ts:1857:16)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

+ Product & version:
CE Store
+ Flutter (or React Native) version: 

+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by hdecode** [comment]
Purchase proof provided. Support has to be waited for a day just for verify purchasing. We have spent two days to find by ourselves.  Could you recommend what node version, expo version and SDK which you use to build and run successfully? I use node  12.18.2 , expo 3.22.3, expo-sdk-38

**Comment by minhcasi** [comment]
@hdecode - could you try to download the nodejs 10.x or 8.x - https://nodejs.org/en/download/releases/

**Comment by hdecode** [comment]
Now I can not run with Expo SDK 38, What SDK version I can run ?

**Comment by hdecode** [comment]
It seems the code is old version Expo SDK 31, so no one support to build??
