### ISSUE TITLE
[ListPro] running setup generate error Error: Cannot find module '@babel/plugin-proposal-decorators'

### ISSUE THREAD

**Issue by qasmaoui** [inspireui/support#433]
**Required Info (please complete the following information):**
 - Product: List PRO
- user name : qasmaoui
**Describe the bug**
after running the CeBuilder on my project 
i got the follwing error on terminal : 

/Users/mac/Desktop/Source/node_modules/metro-babel-register/node_modules/@babel/core/lib/config/files/plugins.js:152
    throw e;
    ^

Error: Cannot find module '@babel/plugin-proposal-decorators' from '/Users/mac/Desktop/Source'
    at Function.module.exports [as sync] (/Users/mac/Desktop/Source/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/Users/mac/Desktop/Source/node_modules/metro-babel-register/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/mac/Desktop/Source/node_modules/metro-babel-register/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/mac/Desktop/Source/node_modules/metro-babel-register/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/mac/Desktop/Source/node_modules/metro-babel-register/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Users/mac/Desktop/Source/node_modules/metro-babel-register/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/mac/Desktop/Source/node_modules/metro-babel-register/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/mac/Desktop/Source/node_modules/metro-babel-register/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/Users/mac/Desktop/Source/node_modules/metro-babel-register/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
Metro Bundler process exited with code 1

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by thangvo9x** [comment]
Hi. Try run yarn add -D @babel/plugin-proposal-decorators
