### ISSUE TITLE
[Fluxstore 1.7.6 patched] How to accept cash-on-delivery only

### ISSUE THREAD

**Issue by netdreamland** [inspireui/support#4508]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: We have set all payment method to false in the config file, and the option "Cash on Delivery" is available in Opencart, 
+ Product & version: [Fluxstore 1.7.6]
+ Flutter (or React Native) version: 1.20.0
+ Testing Device/Simulator: iOS 13.6, iPhone 11 Pro Max
+ Screenshot issues (drag the file to attach here): 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-07 at 17 16 29](https://user-images.githubusercontent.com/12180247/89630359-d87c2300-d8d1-11ea-9dcb-6c8d47a7ceaf.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by netdreamland** [comment]
Here's the log from Android Studio
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3785:9)
#1      _Closure.call (dart:core-patch/function.dart)
#2      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3799:6)
#3      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:3865:12)
#4      Provider._inheritedElementOf (package:provider/src/provider.dart:264:34)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4942 pos 12: 'newWidget.debugCanApplyOutOfTurn()': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
'package:provider/src/provider.dart': Failed assertion: line 200 pos 12: 'context != null': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
[+8623 ms] flutter: [2020-08-07 09:12:14.355287Z][Fluxstore][Cart] build

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3785:9)
#1      _Closure.call (dart:core-patch/function.dart)
#2      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3799:6)
#3      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:3865:12)
#4      Provider._inheritedElementOf (package:provider/src/provider.dart:264:34)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4942 pos 12: 'newWidget.debugCanApplyOutOfTurn()': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
'package:provider/src/provider.dart': Failed assertion: line 200 pos 12: 'context != null': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
[+18088 ms] flutter: [2020-08-07 09:12:32.441097Z][Fluxstore][Cart] build
[+2438 ms] flutter: [2020-08-07 09:12:34.879407Z][Fluxstore][Cart] build
[+1091 ms] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _ShippingAddressState#9417e(lifecycle state: defunct, not mounted)
           This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
           The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
           This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
           #0      State.setState.<anonymous closure> (package:flutter/src/widgets/<…>
```

**Comment by minhtruong315** [comment]
@netdreamland for opencart. you need to EnableAddress, EnableShipping and EnableReview to checkout

**Comment by netdreamland** [comment]
thanks for your answer! is it possible to make the order only `pickup at store` on opencart framework?

**Comment by minhtruong315** [comment]
@netdreamland Fluxstore doesn't support api for pick up at store now.

**Comment by netdreamland** [comment]
OKie @minhtruong315 looking forwards to next version
