### ISSUE TITLE
Quantity add to cart bug

### ISSUE THREAD

**Issue by Trustedbrands** [inspireui/support#4591]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] first issue

We have many products that only have 1 in Quantity in stock. The problem is the customer can add up to 10 to the shopping cart or press the add to cart button as many times as they want. How to fix it so that the customer can only add to the shopping cart?

<img width="313" alt="Skjermbilde 2020-08-13 kl  22 37 55" src="https://user-images.githubusercontent.com/69647853/90186708-ea216700-ddb8-11ea-976c-58653230c973.png">

- [x] second issue
How can I sort the options attributes in the same order as we have on the website?
We use Order by: Custom ordering in the backend of WooCommerce
<img width="337" alt="Skjermbilde 2020-08-13 kl  22 57 06" src="https://user-images.githubusercontent.com/69647853/90186689-dfff6880-ddb8-11ea-8319-83a1d246caea.png">

- [ ] third issue

+ Product & version: Fluxstore V 1.7.7
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: IOS and Android
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Trustedbrands - thank you for the feedback, could you help to share the Filter screen on your website, we are working new upgrade the Filter screen to support for multi-purpose like on your site

**Comment by Trustedbrands** [comment]
@minhcasi 

I need a quick fix on the bug where the customer can add more products than we have in stock.


I attach a picture that shows how the filter on the website is set up. Also attach a video that shows how it works.
https://www.loom.com/share/62a2b29bb7cd4830b4aa98fe609e6e73
![Filter](https://user-images.githubusercontent.com/69647853/90222917-5037d980-de0d-11ea-889f-da341cc8fcb2.PNG)


I also want to make some suggestions on good filtering features that some apps have today. Attaches video of it.
App Boozt: https://drive.google.com/file/d/1DWQ-n6kWfzp-DfgOY2OVS4ify0tTLUTN/view?usp=sharing
App Zalando: https://drive.google.com/file/d/128mJV1N4wa7NsXT9uVkSWijTQyISmlK6/view?usp=sharing

**Comment by minhcasi** [comment]
@Trustedbrands - note with investigating - thank you!

**Comment by Trustedbrands** [comment]
@minhcasi 

Hi I have a problem with create keystore to generate: Debug signing certificate SHA-1

I go to create-keystore.sh and fill in the required information and run the function. But only get this message when I run the function: 
[Storing Downloads/FluxStore-woo-1.7.7/Waior/tools/android/app/mstoresemoFile.keystore]
keytool error: java.io.FileNotFoundException: Downloads/FluxStore-woo-1.7.7/Waior/tools/android/app/mstoresemoFile.keystore (No such file or directory)

java.io.FileNotFoundException: Downloads/FluxStore-woo-1.7.7/Waior/tools/android/app/mstoresemoFile.keystore (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
        at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1345)
        at java.base/sun.security.tools.keytool.Main.run(Main.java:417)
        at java.base/sun.security.tools.keytool.Main.main(Main.java:410)


How do I fix this?

**Comment by minhcasi** [comment]
@Trustedbrands - you could follow this guide from Google - https://flutter.dev/docs/deployment/android#create-a-keystore

**Comment by Trustedbrands** [comment]
@minhcasi Thanks! but now I'm getting this: keytool error: java.lang.Exception: Only one command is allowed: both -exportcert and -list were specified. when I try to run: keytool -exportcert -list -v -alias mstoreapp -keystore android/app/mstore.keystore

**Comment by minhcasi** [comment]
@Trustedbrands - did you run this script - https://tppr.me/aeyrU ?

**Comment by minhcasi** [comment]
Let us know your checking, thanks

**Comment by Trustedbrands** [comment]
@minhcasi  Yes I did run that script.

**Comment by minhcasi** [comment]
@Trustedbrands - please help to double-check the guide and also from your Android SDK, make sure the PATH is setup correctly 

this is my setting
<img width="907" alt="Screen Shot 2020-08-20 at 11 03 59" src="https://user-images.githubusercontent.com/1459805/90715587-dacc7d00-e2d4-11ea-97ed-a797c4f16570.png">

**Comment by minhcasi** [comment]
Let us know your checking - thank you!
