### ISSUE TITLE
[MStore] java.lang.SecurityException: Permission Denial: starting Intent

### ISSUE THREAD

**Issue by rajendar123** [inspireui/support#535]
product Mstore Pro
Purchase code: d0cdb8cc-bf73-45aa-aaaa-b5927cc0e51e
Whenever I try to run react-native run-android. I am seeing below error
Security exception: Permission Denial: starting Intent { flg=0x10000000 cmp=com.inspireui.mstorepro/.MainActivity } from null (pid=16540, uid=2000) not exported from uid
10116

java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.inspireui.mstorepro/.MainActivity } from null (pid=16540, uid=2000) not exported
from uid 10116
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1788)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:717)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:544)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1099)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:486)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5120)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5094)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:479)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16005)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3592)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3291)
        at android.os.Binder.execTransact(Binder.java:731)

**Comment by minhcasi** [comment]
Hi, could you help to install with the CeBuilder to see if can be fix - https://inspireui.com ? Thanks

**Comment by IvoKalu** [comment]
Having same problem and CeBuilder says exactly the same thing.

**Comment by IvoKalu** [comment]
Any help will be appreciated.

**Comment by minhcasi** [comment]
@IvoKalu please follow up the ticket on #549 - and reopen if you have still the issue - thank you!

**Comment by rendyspratama** [comment]
hi @minhcasi, I encountered this problem too, to fix i just add `android:exported="true"` into this line 
`<activity android:name=".MainActivity" android:exported="true" />`

on AndroidManifest.xml

thank you.
