### ISSUE TITLE
[MMV] - Not able to build device or simulator

### ISSUE THREAD

**Issue by mustafamsy** [inspireui/support#739]
I am using latest version of MStore Multi Vendor and tried both CLI and Expo and I always get errors in both of them.

**Purchase code:**
6132dd4c-dc83-4ae7-8e4f-6faa8a635ab2

----------------------------------------------------------------------

When running for cli version:
`react-native run-ios --configuration Release`

I got the following error: 

```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mstoremv.xcworkspace

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/soso/Documents/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/ios/build/mstoremv/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/EXFileSystem.build/Objects-normal/x86_64/EXFileSystemManagerService.o /Users/soso/Documents/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/expo-file-system/ios/EXFileSystem/EXFileSystemManagerService.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/soso/Documents/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/ios/build/mstoremv/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/EXFileSystem.build/Objects-normal/x86_64/EXFileSystemLocalFileHandler.o /Users/soso/Documents/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/expo-file-system/ios/EXFileSystem/EXFileSystemLocalFileHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
. Run CLI with --verbose flag for more details.
```

And when I run the following for cli too: 

`react-native run-ios`

I get the following error

```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mstoremv.xcworkspace

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/soso/Documents/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/ios/build/mstoremv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/EXFileSystem.build/Objects-normal/x86_64/EXFileSystemManagerService.o /Users/soso/Documents/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/expo-file-system/ios/EXFileSystem/EXFileSystemManagerService.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
. Run CLI with --verbose flag for more details.
```

----------------------------------------------------------------------

**When using Expo and run:**
`expo start`

I got the following error:

```
Unable to resolve module `api-ecommerce` from `/Users/soso/Documents/Build/mstore-multi-vendor-v1.3.0/mstore-mv-expo/App.js`: Module `api-ecommerce` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

ABI32_0_0RCTFatal
__37-[ABI32_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
```
I did what suggested regarding watchman and removing and installing again But I get the same error.

**Comment by minhcasi** [comment]
Hi, @mustafamsy - it seems a cache issue - could you try the following script

watchman watch-del-all
rm -rf node_modules && npm install
rm -rf /tmp/metro-bundler-cache-*
rm -rf /tmp/haste-map-react-native-packager-*

Or it is not success, try with the: yarn install && yarn start

**Comment by mustafamsy** [comment]
When I did both 
`rm -rf node_modules && npm install`
And 
`yarn install && yarn start`


I got the following:

```
../ext/channel.cc:292:56: error: too few arguments to function call, expected 2, have 1
  int try_to_connect = (int)info[0]->Equals(Nan::True());
                            ~~~~~~~~~~~~~~~            ^
/Users/soso/.node-gyp/12.4.0/include/node/v8.h:2572:3: note: 'Equals' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> Equals(Local<Context> context,
  ^
/Users/soso/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
1 error generated.
make: *** [Release/obj.target/grpc_node/ext/channel.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/soso/Documents/my Apps/_Apps/Foodyano/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/api-ecommerce/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/soso/Documents/my Apps/_Apps/Foodyano/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/api-ecommerce/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/soso/Documents/my Apps/_Apps/Foodyano/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/api-ecommerce/node_modules/grpc
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/soso/Documents/my Apps/_Apps/Foodyano/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/api-ecommerce/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/soso/Documents/my Apps/_Apps/Foodyano/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/api-ecommerce/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/soso/Documents/my Apps/_Apps/Foodyano/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/soso/Documents/my Apps/_Apps/Foodyano/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/api-ecommerce/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/soso/Documents/my Apps/_Apps/Foodyano/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/api-ecommerce/node_modules/grpc
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/soso/Documents/my Apps/_Apps/Foodyano/Build/mstore-multi-vendor-v1.3.0/mstore-mv-cli/node_modules/api-ecommerce/node
```

**Comment by thangvo9x** [comment]
Try remove folder build in ios folder and run again after removing cache before. Thanks

**Comment by mustafamsy** [comment]
I did that, it did not work.

**Comment by thangvo9x** [comment]
Could you share the Appconfig file for checking? Thanks

**Comment by mustafamsy** [comment]
```
{
  "WooCommerce": {
    "url": "https://foodyano.com",
    "consumerKey": "ck_61b4ca09ac64ad2f97d858dc42a13c3f43239d48",
    "consumerSecret": "cs_378b50f41fac2793f591f0f3b1dfbede83d0cbe5"
  },
  "HorizonLayout": [
    { "tag": 62, "layout": 10 },
    {
      "layout": 14,
      "tag": 32
    },
    {
      "name": "Feature Products",
      "featured": true,
      "image": "",
      "layout": 6
    },
    {
      "name": "On Sale Products",
      "onSale": true,
      "image": "",
      "layout": 2
    },
    {
      "name": "إضافات غذائية",
      "category": 79,
      "image": "",
      "layout": 8
    },
    {
      "name": "شوكولاته",
      "category": 95,
      "image": "",
      "layout": 1
    }
  ],
  "MainColor": "#00BCD4"
}
```

**Comment by thangvo9x** [comment]
hi. Could you provide me full consumerKey for checking?
