### ISSUE TITLE
[FluxStore] - categories are not displayed 

### ISSUE THREAD

**Issue by Sndan** [inspireui/support#783]
1. My issue
when entering a cat this error ::  
```
I/flutter ( 7118): Error: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Iterable<dynamic>'
E/flutter ( 7118): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Iterable<dynamic>'
E/flutter ( 7118): #0      WooCommerce.fetchProductsLayout (package:fstore/services/woo_commerce.dart:83:7)
E/flutter ( 7118): <asynchronous suspension>
E/flutter ( 7118): #1      Services.fetchProductsLayout (package:fstore/services/index.dart:113:25)
E/flutter ( 7118): <asynchronous suspension>
E/flutter ( 7118): #2      _BannerImageItemState.afterFirstLayout (package:fstore/widgets/horizontal/banner_items.dart:48:16)
E/flutter ( 7118): #3      __BannerImageItemState&State&AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
E/flutter ( 7118): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
E/flutter ( 7118): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:966:9)
E/flutter ( 7118): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
E/flutter ( 7118): #7      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 7118): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 7118): #9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 7118): #10     _invoke (dart:ui/hooks.dart:236:10)
E/flutter ( 7118): #11     _drawFrame (dart:ui/hooks.dart:194:3)
E/flutter ( 7118): 
I/flutter ( 7118): Error: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Iterable<dynamic>'
E/flutter ( 7118): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Iterable<dynamic>'
E/flutter ( 7118): #0      WooCommerce.fetchProductsLayout (package:fstore/services/woo_commerce.dart:83:7)
E/flutter ( 7118): <asynchronous suspension>
E/flutter ( 7118): #1      Services.fetchProductsLayout (package:fstore/services/index.dart:113:25)
E/flutter ( 7118): <asynchronous suspension>
E/flutter ( 7118): #2      _BannerImageItemState.afterFirstLayout (package:fstore/widgets/horizontal/banner_items.dart:48:16)
E/flutter ( 7118): #3      __BannerImageItemState&State&AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
E/flutter ( 7118): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
E/flutter ( 7118): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:966:9)
E/flutter ( 7118): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
E/flutter ( 7118): #7      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 7118): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 7118): #9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 7118): #10     _invoke (dart:ui/hooks.dart:236:10)
E/flutter ( 7118): #11     _drawFrame (dart:ui/hooks.dart:194:3)
```
2. Screenshots
![image](https://user-images.githubusercontent.com/110978/61132392-f1928480-a4c3-11e9-8d6f-3fb341f0e4d5.png)

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/110978/61132494-230b5000-a4c4-11e9-9c1f-d8bf97efe961.png)

3. Config files (optional)
```
{
  "server": {
    "type": "woo",
    "url": "http://xx.xx",
    "consumerKey": "xx",
    "consumerSecret": "xx",

    "blog": "http://x.x",
    "forgetPassword": "http://x.x/wp-login.php?action=lostpassword"
  },
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true
    },
    {
      "layout": "iconCategory"
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "items": [
        {
          "category": 38,
          "image": "https://user-images.githubusercontent.com/1459805/59846818-12672e80-938b-11e9-8184-5f7bfe66f1a2.png",
          "padding": 15.0
        },
        {
          "category": 38,
          "image": "https://user-images.githubusercontent.com/1459805/60091575-1f12ca80-976f-11e9-962c-bdccff60d143.png",
          "padding": 15.0
        },
        {
          "category": 38,
          "image": "https://user-images.githubusercontent.com/1459805/60091808-a19b8a00-976f-11e9-9cc7-576ca05c2442.png",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "category": 38,
          "image": "https://user-images.githubusercontent.com/1459805/59846820-12672e80-938b-11e9-8fa6-b331b7db331d.png",
          "padding": 5.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "category": 38,
          "image": "https://user-images.githubusercontent.com/1459805/59846823-12ffc500-938b-11e9-8d93-65ead3d6b1dd.png",
          "padding": 5.0
        },
        {
          "category": 38,
          "image": "https://user-images.githubusercontent.com/1459805/59846824-12ffc500-938b-11e9-8d5a-fc42cb1b7658.png",
          "padding": 5.0
        }
      ]
    },
    {
      "name": {
        "en": "Woman Collections",
        "ab": "مجموعات المرأة",
        "vi": "Bộ sưu tập cho phụ nữ"
      },
      "image": "",
      "layout": "threeColumn",
      "category": 38
    },
    {
      "name": {
        "en": "Man Collections",
        "ab": "مجموعات الرجل",
        "vi": "Bộ sưu tập cho đàn ông"
      },
      "image": "",
      "layout": "twoColumn",
      "category": 38
    },
    {
      "name": {
        "en": "Our Blog Posts",
        "ab": "بلوق وظائف",
        "vi": "Blog của chúng tôi"
      },
      "layout": "blog"
    },
    {
      "name": {
        "en": "Share your look",
        "ab": "مشاركة مظهرك",
        "vi": "Chia sẻ cái nhìn của bạn"
      },
      "layout": "instagram",
      "tag": "koreanmodel"
    }
  ],
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list"
  }
}
```

**Comment by Sndan** [comment]
?

**Comment by minhcasi** [comment]
can you share the config file to support@inspireui.com - we could not check with the domain xx.xx

**Comment by Sndan** [comment]
you want mu domain ?

**Comment by minhcasi** [comment]
I mean to the domain as consumse keys as we could not to check with your config file
```
"url": "http://xx.xx",
    "consumerKey": "xx",
    "consumerSecret": "xx",
```

**Comment by Sndan** [comment]
do you want me to provide the domain and keys ?
