### ISSUE TITLE
BUILD FAILED  Mstore pro

### ISSUE THREAD

**Issue by 007asom** [inspireui/support#917]
Hello
I'm trying to build a new app

BUILD FAILED in 9m 6s

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at runOnAllDevices (\mstore-3.9.4b\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (\mstore-3.9.4b\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at \mstore-3.9.4b\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Command.handleAction (\mstore-3.9.4b\mstore-pro\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:7)

**Comment by minhcasi** [comment]
Hi, could you try to check this document to see if you can run the Example project on this guide - https://facebook.github.io/react-native/docs/getting-started.html

Also, provide us a full screenshot of the issue - thank you!
